"""Build the linear-regression baseline deliverables from their sources.

Writes two files, both GENERATED -- never edit them by hand:

  stage1_verbatim.py        the Stage-1 definitions the baseline reuses, copied VERBATIM out of
                            GAT_LSTM_NN_Publication_superresolution.ipynb (graph builder,
                            resampling, the dataset class, the split utilities, the evaluation
                            mask filter, the standardiser and the per-window metric function).
  Linear_Regression.ipynb   the reviewer-facing notebook, converted from the percent-format
                            source _Linear_Regression_cells.py with nbformat.

Why copy from the super-resolution notebook: it is the maintained copy, and with its Stage-1
flags (out_N=None, pair_windows_across_node_counts=False, noise off) it reproduced the v5
split, normalisers and test metrics (patch sr-20 test; job 402698 pass B). The cluster
rebuild of 2026-09-05 changed the environment and the loss, not the data pipeline.

The hash below covers exactly the copied sources, so an unrelated edit to the source notebook
(e.g. a _MODE toggle in cell a04f1f5f) does not trip it, but an edit to anything copied does.

Usage:  python _build_linear_regression_nb.py            (idempotent)
        python _build_linear_regression_nb.py --rehash   (print the hash of the current sources)
"""
from __future__ import annotations

import ast
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC_NB = ROOT / "GAT_LSTM_NN_Publication_superresolution.ipynb"
CELLS_SRC = ROOT / "_Linear_Regression_cells.py"
OUT_MODULE = ROOT / "stage1_verbatim.py"
OUT_NB = ROOT / "Linear_Regression.ipynb"

# (cell id, None = the whole cell | name of one top-level def/class to slice out)
COPY_UNITS = [
    ("66cf027f", None),                                  # MOORING_PROPERTIES, build_mooring_graph
    ("4d3988c6", None),                                  # resample_fe_output
    ("a5660cf4", None),                                  # features + MooringSequenceDatasetPositionTension
    ("858f4194", None),                                  # split utilities
    ("81d71e4b", "_sr22_filter_windows"),                # evaluation-mask test-window filter
    ("8e7ef9e9", "FeatureStandardizer"),                 # standardiser (target transform)
    ("9e030261", "compute_physical_metrics_per_target"),  # per-window metrics
]
EXPECTED_SHA = "00e848f601610783"   # sha256[:16] of the concatenated copied sources

HEADER = '''"""GENERATED by _build_linear_regression_nb.py -- DO NOT EDIT.

Stage-1 definitions copied VERBATIM from GAT_LSTM_NN_Publication_superresolution.ipynb,
one block per source cell (the cell id heads each block). Source-content hash: {sha}.

Only this header is new: the imports the cells expect, a small stand-in for
torch_geometric.data.Data when PyG is not installed, and the module-level tables the
split utilities read (set by linear_regression_lib.set_tables).
"""
from __future__ import annotations   # annotations such as `cfg: TrainingConfig` stay unevaluated

import copy
import math
import os
import random
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
from torch.utils.data import Dataset

try:
    from torch_geometric.data import Data
except ImportError:                    # build_mooring_graph only uses Data as a container
    class Data:
        def __init__(self, **kw):
            for k, v in kw.items():
                setattr(self, k, v)

        def clone(self):
            return copy.deepcopy(self)

# Read by valid_window_starts_inside_raw_interval / _snap_windows_in (cell 858f4194).
EXCLUDE_ARTIFACT_WINDOWS = True
ARTIFACT_SAMPLES = {{}}
SNAP_EVENT_TIMES = {{}}
'''


def _slice(src: str, name: str) -> str:
    """The source of one top-level def/class of a cell, exactly as written."""
    tree = ast.parse(src)
    lines = src.splitlines()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name == name:
            start = node.lineno - 1
            if node.decorator_list:
                start = node.decorator_list[0].lineno - 1
            return "\n".join(lines[start:node.end_lineno])
    raise KeyError(f"{name} not found")


def copied_blocks():
    nb = json.loads(SRC_NB.read_text(encoding="utf-8"))
    cells = {c.get("id"): "".join(c["source"]) for c in nb["cells"]}
    blocks = []
    for cid, name in COPY_UNITS:
        src = cells[cid] if name is None else _slice(cells[cid], name)
        blocks.append((cid, name, src))
    sha = hashlib.sha256("\n\n".join(b[2] for b in blocks).encode("utf-8")).hexdigest()[:16]
    return blocks, sha


def build_module():
    blocks, sha = copied_blocks()
    if sha != EXPECTED_SHA:
        raise SystemExit(
            f"[build] copied Stage-1 sources changed: sha {sha} != expected {EXPECTED_SHA}.\n"
            "        Review the change in the source notebook, then update EXPECTED_SHA.")
    parts = [HEADER.format(sha=sha)]
    for cid, name, src in blocks:
        what = "whole cell" if name is None else name
        parts.append(f"\n\n# {'=' * 75}\n# VERBATIM from cell {cid} ({what})\n# {'=' * 75}\n")
        parts.append(src.rstrip() + "\n")
    text = "".join(parts)
    ast.parse(text)
    OUT_MODULE.write_text(text, encoding="utf-8", newline="\n")
    print(f"[build] wrote {OUT_MODULE.name} ({len(text.splitlines())} lines, sources sha {sha})")


def parse_percent_cells(text: str):
    """Split a percent-format script into (cell_type, source) pairs.

    '# %%' starts a code cell, '# %% [markdown]' a markdown cell whose lines are
    '# '-prefixed comment lines (the prefix is stripped)."""
    cells, kind, buf = [], None, []

    def flush():
        if kind is None:
            return
        body = "\n".join(buf).strip("\n")
        if kind == "markdown":
            body = "\n".join(l[2:] if l.startswith("# ") else l.lstrip("#") for l in body.splitlines())
        cells.append((kind, body))

    for line in text.splitlines():
        if line.startswith("# %%"):
            flush()
            kind = "markdown" if "[markdown]" in line else "code"
            buf = []
        elif kind is not None:
            buf.append(line)
    flush()
    return cells


def build_notebook():
    import nbformat
    from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

    cells = parse_percent_cells(CELLS_SRC.read_text(encoding="utf-8"))
    nb = new_notebook()
    nb.metadata["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
    nb.metadata["language_info"] = {"name": "python"}
    for i, (kind, body) in enumerate(cells):
        if kind == "code":
            ast.parse(body)
            cell = new_code_cell(body)
        else:
            cell = new_markdown_cell(body)
        cell["id"] = f"lr{i:02d}"
        nb.cells.append(cell)
    nbformat.validate(nb)
    OUT_NB.write_text(nbformat.writes(nb), encoding="utf-8", newline="\n")
    print(f"[build] wrote {OUT_NB.name} ({len(cells)} cells)")


if __name__ == "__main__":
    if "--rehash" in sys.argv:
        print(copied_blocks()[1])
        sys.exit(0)
    build_module()
    build_notebook()
