"""Linear-regression baselines for the Stage-1 (matched-resolution) reconstruction task.

Companion module of Linear_Regression.ipynb. It lives in a .py file (not in the notebook)
for one reason: the training and evaluation passes run in a process pool, and on Windows a
worker process can only call functions it can import.

What is reused from Stage 1, unchanged (module `stage1_verbatim`, generated by
_build_linear_regression_nb.py straight from the Stage-1 notebook code):
  * the input features  -- build_mooring_graph, resample_fe_output, and the per-window
    feature code of MooringSequenceDatasetPositionTension. The batched port below is checked
    against the class itself and must agree exactly (GATE 2 in the notebook);
  * the split           -- build_leakage_aware_splits and _cap_split_windows, run on
    header-only stand-ins, then the evaluation-mask screen _sr22_filter_windows;
  * the metrics         -- compute_physical_metrics_per_target per window, then the
    aggregation of evaluate() (cell 8f268a8b) and the CSV layout of test_model() (cell
    d75ee9f2), ported below as EvalAccumulator and write_test_outputs.

The four linear models (a ladder: each adds information the GAT+BiLSTM has):
  LR0_static     T = tension0, the station's static (t = 0) tension. No fit.
  LR1_pointwise  ordinary least squares on the station's own 34 model inputs at one instant
                 (12 static + 22 dynamic): exactly what the GAT receives per station.
  LR2_line       LR1 + the 9 motion-derived channels of the fairlead, of the two neighbouring
                 stations and their mean along the line, at the same instant.
  LR3_lagged     LR2 + the station's and the fairlead's 9 channels at lags of +-0.1 .. +-5 s,
                 i.e. a non-causal linear filter over the window, like the bidirectional LSTM.
  LR4_lagged40   LR3 + the same channels at every 1 s out to +-40 s: the filter's memory spans
                 most of the 100 s window (lags are clamped at its edges, as the BiLSTM also
                 sees only the window). LR3's columns are LR4's leading columns. LR4 has its own
                 standardiser and its own caches, so LR0-LR3 are computed exactly as before.

All are fitted by ordinary least squares, the exact minimiser of the mean squared error.
The fit is streamed: every block of rows [1, z, y] (z = standardised inputs) updates the
triangular factor R of a QR decomposition, R <- qr([R; block]). This is the backward-stable
way to solve least squares in one pass; the normal equations (X^T X) square the condition
number and lose near-collinear directions (measured on a small subset: 1.3e-5 excess squared
error, against 2e-8 for QR). LR3 adds a small ridge term, picked on the validation split.
"""
from __future__ import annotations

import collections
import csv
import hashlib
import json
import math
import os
import statistics
import time
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import torch

import stage1_verbatim as S1

# ----------------------------------------------------------------------------- constants
LOC_IDS = (1, 3, 4, 5, 6, 7, 8, 9, 10, 11)
DEV_SITES = (1, 3, 4, 5, 6, 7, 8, 9)
N_CASES = 300
LAYOUTS = (4, 5, 6, 7, 8, 10, 12, 15, 18, 21)
WINDOW_LEN = 1000
N_FULL = 21
CONTACT_FLAG_IDX = 4
N_STATIC, N_DYN, N_BASE = 12, 22, 9
# Stage 1's tension normaliser (v5 checkpoint, criterion_state_dict t_mean / t_std). The metric
# code receives normalised tensors and maps them back, exactly as in evaluate(); using the same
# constants makes the truth side of every metric identical to Stage 1's.
TARGET_MEAN = 2791.087646484375
TARGET_STD = 2727.0
LAGS = (-50, -20, -10, -5, -2, -1, 1, 2, 5, 10, 20, 50)
# LR4: LR3's lags, then every 1 s out to +-40 s (10-sample steps; the motion has almost no content
# above 0.5 Hz, so 1 s resolves it). LR3's lags come FIRST, so LR3's columns are the leading
# columns of LR4's design: LR3 is nested in LR4 as LR1 is in LR2.
LONG_LAG_MAX = 400                                     # samples = 40 s
LAGS_LONG = LAGS + tuple(s * t for t in range(10, LONG_LAG_MAX + 1, 10)
                         if t not in {abs(x) for x in LAGS} for s in (-1, 1))
SNAP_NBHD_OFF = (-2, -1, 0, 1, 2)       # as _SR20_OFF in the Stage-1 dump code
SNAP_NBHD_MAXN = 21
# Cases dropped whole in Stage 1 (cell f80f8d84): non-finite records and two records shorter
# than one window. Every other corrupt sample is handled per window by the artifact mask.
CORRUPT_CASES_NONFINITE = frozenset({(7, 16), (7, 32), (7, 83), (7, 132), (7, 137), (7, 212),
                                     (7, 214), (7, 220), (7, 225), (7, 229), (11, 61)})
CORRUPT_CASES_TOO_SHORT = frozenset({(5, 202), (5, 262)})
CORRUPT_CASES = CORRUPT_CASES_NONFINITE | CORRUPT_CASES_TOO_SHORT

STATIC_NAMES = ["s_over_L", "is_anchor", "is_fairlead", "is_intermediate", "x0", "z0",
                "nodal_mass", "diameter", "area", "submerged_weight", "z_bed", "tension0"]
DYN_NAMES = (["x_abs", "z_abs", "x_vel", "z_vel", "contact_flag", "penetration_depth",
              "bed_reaction_z", "F_drag_t", "F_drag_n"] + list(S1.ENV_COL_NAMES))
BASE_NAMES = DYN_NAMES[:N_BASE]
# Inputs that are EXACT linear functions of other inputs (build_mooring_graph): the three station
# flags sum to one, and submerged_weight = (1 - rho_w A / m') g * nodal_mass. They carry no
# information a linear model can use; kept in the fit, float32 rounding makes each pair differ by
# ~1e-7 and least squares would fit that noise with huge cancelling weights (+-1e8 measured).
EXACT_DUPLICATES = ("static:is_intermediate", "static:submerged_weight")

# Memory guards of run_parallel; the notebook sets them from the Slurm allocation or from the
# memory free on the machine. One worker peaks at ~0.9 GB (pass A, measured); on 2026-09-30 ten
# workers on a 16 GB laptop paged it until it froze.
RSS_LIMIT_GB = 10.0     # abort if the resident memory of this process and its workers exceeds this
MIN_AVAIL_GB = 0.0      # abort if the machine's free memory falls below this (0 = off)


def n_cols(blocks, lags=LAGS):
    """Number of input columns (without the intercept) of a design."""
    p = 0
    if "own" in blocks:
        p += N_STATIC + N_DYN
    if "ctx" in blocks:
        p += 4 * N_BASE
    if "lag" in blocks:
        p += 2 * N_BASE * len(lags)
    return p


RUNGS = {   # rung -> design blocks (LR0 has none: it is not fitted)
    "LR0_static": (),
    "LR1_pointwise": ("own",),
    "LR2_line": ("own", "ctx"),
    "LR3_lagged": ("own", "ctx", "lag"),
    "LR4_lagged40": ("own", "ctx", "lag"),
}
RUNG_LAGS = {"LR4_lagged40": LAGS_LONG}   # every other rung uses LAGS
FULL_BLOCKS = ("own", "ctx", "lag")


def rung_lags(rung):
    return RUNG_LAGS.get(rung, LAGS)


def rung_cols(rung):
    """Number of input columns of a rung (0 for LR0)."""
    return n_cols(RUNGS[rung], rung_lags(rung))


def column_names(blocks=FULL_BLOCKS, lags=LAGS):
    names = []
    if "own" in blocks:
        names += [f"static:{n}" for n in STATIC_NAMES] + [f"dyn:{n}" for n in DYN_NAMES]
    if "ctx" in blocks:
        for src in ("fairlead", "prev", "next", "linemean"):
            names += [f"{src}:{n}" for n in BASE_NAMES]
    if "lag" in blocks:
        for tau in lags:
            names += [f"own@{tau:+d}:{n}" for n in BASE_NAMES]
            names += [f"fairlead@{tau:+d}:{n}" for n in BASE_NAMES]
    return names


# ----------------------------------------------------------------------------- tables
def read_sample_table(path):
    """artifact_samples*.csv -> {(loc, case): sorted sample indices} (column bad_t)."""
    out = {}
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            out[(int(r["loc"]), int(r["case"]))] = sorted(int(t) for t in r["bad_t"].split())
    return out


def read_catalogue(path):
    """snap_catalogue*.csv -> ({(loc, case): sorted event samples}, {(loc, case, t): node})."""
    times, node = collections.defaultdict(list), {}
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            k = (int(r["loc"]), int(r["case"]))
            times[k].append(int(r["t"]))
            node[(k[0], k[1], int(r["t"]))] = int(r["node"])
    return {k: sorted(v) for k, v in times.items()}, node


def load_tables(root):
    """The training mask, the evaluation-only extra samples and the snap catalogue."""
    root = Path(root)
    artifact = read_sample_table(root / "artifact_samples.csv")
    eval_mask = read_sample_table(root / "artifact_samples_cat.csv")
    catenary = {}
    for k, v in eval_mask.items():
        extra = sorted(set(v) - set(artifact.get(k, ())))
        if extra:
            catenary[k] = extra
    snap_times, snap_node = read_catalogue(root / "snap_catalogue_cat.csv")
    return dict(artifact=artifact, eval_mask=eval_mask, catenary=catenary,
                snap_times=snap_times, snap_node=snap_node)


def set_tables(artifact):
    """Install the training mask where the verbatim split utilities read it."""
    S1.EXCLUDE_ARTIFACT_WINDOWS = True
    S1.ARTIFACT_SAMPLES = artifact
    S1.SNAP_EVENT_TIMES = {}     # read only when snap_oversample_frac > 0 (Stage 1: 0)


SPLIT_FIELDS = ("split_seed", "test_time_fraction", "raw_block_len",
                "train_fraction_within_dev_blocks", "train_lc_ids", "test_extra_lc_ids",
                "node_counts", "max_train_windows", "max_val_windows", "max_test_windows",
                "window_len", "snap_oversample_frac")


def load_split_config(path):
    """The Stage-1 run configuration (config.json of the shipped v5 model), split fields only."""
    cfg = json.loads(Path(path).read_text(encoding="utf-8"))
    ns = SimpleNamespace(**{k: cfg[k] for k in SPLIT_FIELDS})
    ns.pair_windows_across_node_counts = False       # Stage 1 draws windows per node count
    ns.tension_mape_min = float(cfg.get("tension_mape_min", 1000.0))
    ns.n_fit_windows = int(cfg.get("n_fit_windows", 5000))
    return ns


# ----------------------------------------------------------------------------- split
class StubDataset:
    """Header-only stand-in for MooringSequenceDatasetPositionTension.

    build_leakage_aware_splits reads only num_steps, window_len, len(), target_N and the
    graph's location/case ids, so no time series is opened to rebuild the split."""

    def __init__(self, lc, case, target_n, num_steps, window_len=WINDOW_LEN):
        self.num_steps = int(num_steps)
        self.window_len = int(window_len)
        self.target_N = int(target_n)
        self.graph_data = SimpleNamespace(batch_location_id=int(lc), case_id=int(case))

    def __len__(self):
        return self.num_steps - self.window_len + 1


def case_dir(cache_dir, lc, case):
    return Path(cache_dir) / f"loc{lc:02d}" / f"case_{case:04d}"


def record_lengths(cache_dir, corrupt=CORRUPT_CASES):
    """Record length of every in-use case, read from the .npy header only."""
    out = {}
    for lc in LOC_IDS:
        for case in range(1, N_CASES + 1):
            if (lc, case) in corrupt:
                continue
            out[(lc, case)] = int(np.load(case_dir(cache_dir, lc, case) / "x_abs.npy",
                                          mmap_mode="r").shape[0])
    return out


def regenerate_split(cache_dir, cfg, catenary, corrupt=CORRUPT_CASES):
    """The Stage-1 split, rebuilt with the verbatim utilities in Stage 1's dict order
    (location -> case -> node count, as build_lazy_load_case_datasets builds it).

    Returns flat window keys (loc, case, N, start): train, val, test (the published
    50,000-window draw) and test_screened (minus windows covering an evaluation-mask sample)."""
    lengths = record_lengths(cache_dir, corrupt)
    ds = {}
    for (lc, case), n in lengths.items():          # insertion order = loc -> case
        if n < cfg.window_len:
            continue
        for nc in LAYOUTS:
            ds[(lc, case, nc)] = StubDataset(lc, case, nc, n, cfg.window_len)
    sp = S1.build_leakage_aware_splits(ds, cfg)
    sp = S1._cap_split_windows(sp, cfg)
    screened = S1._sr22_filter_windows(sp["test"], catenary, cfg.window_len)
    flat = lambda pairs: [(k[0], k[1], k[2], int(w)) for k, w in pairs]   # noqa: E731
    return dict(train=flat(sp["train"]), val=flat(sp["val"]), test=flat(sp["test"]),
                test_screened=flat(screened), lengths=lengths)


def keys_sha(keys):
    return hashlib.sha256(repr(sorted(keys)).encode()).hexdigest()[:16]


# ----------------------------------------------------------------------------- case data
def load_case(cache_dir, lc, case):
    d = case_dir(cache_dir, lc, case)
    return dict(x=np.load(d / "x_abs.npy"), z=np.load(d / "z_abs.npy"),
                T=np.load(d / "tension.npy"),
                s0=np.array(np.load(d / "reference.npy", mmap_mode="r")[0]),
                env=np.load(d / "env.npy"))


def case_graph(arr, lc, case, n):
    """The station graph exactly as build_lazy_load_case_datasets (cell fbac801f) makes it."""
    x0 = torch.tensor(arr["x"][0], dtype=torch.float32)
    z0 = torch.tensor(arr["z"][0], dtype=torch.float32)
    t0 = torch.tensor(arr["T"][0], dtype=torch.float32)
    s0 = torch.tensor(arr["s0"], dtype=torch.float32)
    env_row = arr["env"]
    graph = S1.build_mooring_graph(
        x0_nodes=S1.resample_fe_output(x0.unsqueeze(0), n).squeeze(0),
        z0_nodes=S1.resample_fe_output(z0.unsqueeze(0), n).squeeze(0),
        tension0_nodes=S1.resample_fe_output(t0.unsqueeze(0), n).squeeze(0),
        s0_nodes=S1.resample_fe_output(s0.unsqueeze(0), n).squeeze(0),
        water_depth=float(env_row[0]),
        depths_current=[float(env_row[i]) for i in (3, 5, 7, 9, 11)],
    )
    graph.batch_location_id = lc
    graph.case_id = case
    return graph


def resampled_record(arr, n):
    """x, z and tension of the whole record at n stations. Resampling acts row by row
    (along the line), so slicing afterwards equals resampling each window."""
    return {k: S1.resample_fe_output(torch.tensor(arr[k], dtype=torch.float32), n)
            for k in ("x", "z", "T")}


# ----------------------------------------------------------------------------- features
def _time_gradient_b(sig, dt=S1.FEATURE_DT):
    """S1._time_gradient along dim 1 of [B, W, N], op for op."""
    grad = torch.empty_like(sig)
    grad[:, 1:-1] = (sig[:, 2:] - sig[:, :-2]) / (2.0 * dt)
    grad[:, 0] = (sig[:, 1] - sig[:, 0]) / dt
    grad[:, -1] = (sig[:, -1] - sig[:, -2]) / dt
    return grad


def _unit_tangents_b(x_abs, z_abs):
    """S1._unit_tangents along dim 2 of [B, W, N], op for op."""
    def _node_diff(sig):
        d = torch.empty_like(sig)
        d[..., 1:-1] = sig[..., 2:] - sig[..., :-2]
        d[..., 0] = sig[..., 1] - sig[..., 0]
        d[..., -1] = sig[..., -1] - sig[..., -2]
        return d
    dx = _node_diff(x_abs)
    dz = _node_diff(z_abs)
    mag = torch.sqrt(dx * dx + dz * dz).clamp_min(1e-8)
    return dx / mag, dz / mag


def batched_dynamic_features(x_abs, z_abs, graph, env_row, contact_tol=1e-6):
    """The 22 dynamic node inputs of a stack of windows, [B, W, N] -> [B, W, N, 22].

    A batched port of steps 3-6 of MooringSequenceDatasetPositionTension.__getitem__
    (sensor noise off). Same operations in the same order, so the result equals the class
    exactly (GATE 2)."""
    n = x_abs.shape[-1]
    node_len = torch.full((n,), float(graph.L0))
    node_len[0] *= 0.5
    node_len[-1] *= 0.5
    node_len = node_len.view(1, 1, n)

    x_vel = _time_gradient_b(x_abs)
    z_vel = _time_gradient_b(z_abs)

    z_bed = graph.z_bed_node.detach().cpu().view(1, 1, n)
    contact_flag = (z_abs <= z_bed + contact_tol).float()
    penetration = torch.clamp(z_bed - z_abs, min=0.0)
    submerged_w = graph.x[:, 9].detach().cpu().view(1, 1, n)
    contact_area = graph.diameter * node_len
    v_z = z_vel
    bed_reaction = torch.where(
        contact_flag > 0.0,
        submerged_w + (graph.k_b * penetration - graph.c_b * v_z) * contact_area,
        torch.zeros_like(submerged_w),
    )

    tx, tz = _unit_tangents_b(x_abs, z_abs)
    v_t = x_vel * tx + z_vel * tz
    v_n = -x_vel * tz + z_vel * tx
    A_n = graph.diameter * node_len
    A_t = math.pi * graph.diameter * node_len
    F_drag_t = -0.5 * S1.RHO_WATER * graph.Cd_t * A_t * v_t * v_t.abs()
    F_drag_n = -0.5 * S1.RHO_WATER * graph.Cd_n * A_n * v_n * v_n.abs()

    dyn = torch.stack([x_abs, z_abs, x_vel, z_vel, contact_flag, penetration, bed_reaction,
                       F_drag_t, F_drag_n], dim=-1)
    env = env_row.view(1, 1, 1, -1).expand(dyn.shape[0], dyn.shape[1], n, -1)
    return torch.cat([dyn, env], dim=-1)


def design(graph, dyn, blocks, lags=LAGS, rows=None):
    """Design matrix [B, R, N, P] (float32) for the requested blocks.

    rows: the time rows to keep (None = all). Lagged values are taken from the whole window
    and clamped at its edges -- the linear filter, like the BiLSTM, sees only the window."""
    b, w, n, _ = dyn.shape
    t_idx = torch.arange(w) if rows is None else torch.as_tensor(rows, dtype=torch.long)
    r = t_idx.numel()
    base = dyn[..., :N_BASE]
    parts = []
    if "own" in blocks:
        parts.append(graph.x.view(1, 1, n, N_STATIC).expand(b, r, n, N_STATIC))
        parts.append(dyn[:, t_idx])
    if "ctx" in blocks:
        br = base[:, t_idx]
        prev_i = torch.clamp(torch.arange(n) - 1, 0, n - 1)
        next_i = torch.clamp(torch.arange(n) + 1, 0, n - 1)
        parts += [br[:, :, n - 1:n].expand(b, r, n, N_BASE), br[:, :, prev_i], br[:, :, next_i],
                  br.mean(dim=2, keepdim=True).expand(b, r, n, N_BASE)]
    if "lag" in blocks:
        for tau in lags:
            ti = torch.clamp(t_idx + tau, 0, w - 1)
            lb = base[:, ti]
            parts += [lb, lb[:, :, n - 1:n].expand(b, r, n, N_BASE)]
    return torch.cat(parts, dim=-1)


def static_prediction(graph, w_len):
    """LR0: the station's static tension, held constant over the window, [W, N]."""
    t0 = graph.x[:, 11]
    return t0.view(1, -1).expand(w_len, -1)


# ----------------------------------------------------------------------------- workers
def worker_init(n_threads=1):
    """One BLAS/torch thread per worker, so a pool of workers does not oversubscribe."""
    torch.set_num_threads(n_threads)
    try:
        from threadpoolctl import threadpool_limits
        global _TPL
        _TPL = threadpool_limits(n_threads)
    except ImportError:
        pass


def _by_case(keys):
    """Group window keys as {(loc, case): {N: [starts]}} keeping first-seen order."""
    g = collections.OrderedDict()
    for lc, case, nc, s in keys:
        g.setdefault((lc, case), collections.OrderedDict()).setdefault(nc, []).append(s)
    return g


def make_tasks(kind, keys, cases_per_task, **extra):
    """Split window keys into tasks of `cases_per_task` cases of one location each."""
    grouped = _by_case(keys)
    by_loc = collections.OrderedDict()
    for (lc, case), per_n in grouped.items():
        by_loc.setdefault(lc, []).append((case, [(nc, st) for nc, st in per_n.items()]))
    tasks = []
    for lc in sorted(by_loc):
        cl = by_loc[lc]
        for i in range(0, len(cl), cases_per_task):
            tasks.append(dict(kind=kind, lc=lc, cases=cl[i:i + cases_per_task],
                              tid=f"{kind}_{lc:02d}_{i // cases_per_task:03d}", **extra))
    return tasks


def _chunk(n_rows_per_window, n_stations, p, budget_bytes=160e6, cap=16):
    per = n_rows_per_window * n_stations * (p + 1) * 8.0
    return max(1, min(cap, int(budget_bytes // max(per, 1.0))))


def _phase_rows(start, w_len, stride):
    """Rows of a window whose ABSOLUTE sample index is a multiple of `stride`, so windows
    that overlap keep the same samples."""
    first = (-int(start)) % stride
    return np.arange(first, w_len, stride)


def _qr_update(R, M):
    """Triangular factor of [R; M] (Householder QR, LAPACK geqrf)."""
    return np.linalg.qr(M if R is None else np.vstack([R, M]), mode="r")


def _square(R, q):
    """Pad a factor built from fewer than q rows to q x q."""
    if R is None:
        return np.zeros((q, q))
    if R.shape[0] < q:
        R = np.vstack([R, np.zeros((q - R.shape[0], q))])
    return R


def _fit_task(task):
    """Least-squares factor (or raw column moments) over the task's windows.

    kind 'moments': sum and sum of squares of every raw design column.
    kind 'fit'    : triangular factor R of the rows [1, z, y], z = (x - mu) / sd, per group
                    (the two halves of the LR3 pass; one group otherwise)."""
    cache, lc = task["cache_dir"], task["lc"]
    blocks, lags = task["blocks"], tuple(task.get("lags", LAGS))
    stride = int(task.get("stride", 1))
    group_of = task.get("group_of")          # {(case, N, start): 0 or 1}, LR3 pass only
    p = n_cols(blocks, lags)
    q = p + 2
    n_groups = int(task.get("n_groups", 1))
    if task["kind"] == "moments":
        s1, s2, cnt = np.zeros(p), np.zeros(p), 0
    else:
        mu, sd = np.asarray(task["mu"])[:p], np.asarray(task["sd"])[:p]
        R = [None] * n_groups
        cnt_g = np.zeros(n_groups)
    n_windows = 0
    for case, per_n in task["cases"]:
        arr = load_case(cache, lc, case)
        env_row = torch.tensor(arr["env"], dtype=torch.float32)
        for nc, starts in per_n:
            graph = case_graph(arr, lc, case, nc)
            rec = resampled_record(arr, nc)
            # windows grouped by (row phase, group) so a batch shares its rows
            buckets = collections.defaultdict(list)
            for s in starts:
                ph = (-int(s)) % stride
                grp = 0 if group_of is None else int(group_of[(case, nc, s)])
                buckets[(ph, grp)].append(s)
            for (ph, grp), ss in buckets.items():
                rows = None if stride == 1 else _phase_rows(ss[0], WINDOW_LEN, stride)
                r = WINDOW_LEN if rows is None else len(rows)
                # a larger block per QR update for a wide design (LR4): re-factoring the
                # stacked R costs ~q/rows of the update, so a block should hold >> q rows
                step = _chunk(r, nc, q, budget_bytes=float(task.get("budget_bytes", 100e6)),
                              cap=int(task.get("chunk_cap", 16)))
                for i in range(0, len(ss), step):
                    st = torch.tensor(ss[i:i + step])
                    idx = st[:, None] + torch.arange(WINDOW_LEN)[None]
                    dyn = batched_dynamic_features(rec["x"][idx], rec["z"][idx], graph, env_row)
                    X = design(graph, dyn, blocks, lags, rows).reshape(-1, p).numpy().astype(np.float64)
                    tw = rec["T"][idx] if rows is None else rec["T"][idx][:, torch.as_tensor(rows)]
                    y = tw.reshape(-1).numpy().astype(np.float64)
                    n_windows += len(st)
                    if task["kind"] == "moments":
                        s1 += X.sum(axis=0)
                        s2 += np.einsum("ij,ij->j", X, X)
                        cnt += X.shape[0]
                    else:
                        M = np.empty((X.shape[0], q))
                        M[:, 0] = 1.0
                        np.subtract(X, mu, out=M[:, 1:p + 1])
                        M[:, 1:p + 1] /= sd
                        M[:, -1] = y
                        R[grp] = _qr_update(R[grp], M)
                        cnt_g[grp] += y.size
    if task["kind"] == "moments":
        return dict(s1=s1, s2=s2, n=cnt, n_windows=n_windows)
    return dict(R=np.stack([_square(r, q) for r in R]), n=cnt_g, n_windows=n_windows)


def _target_norm():
    tn = S1.FeatureStandardizer((0,))
    tn.mean = torch.tensor([TARGET_MEAN], dtype=torch.float32)
    tn.std = torch.tensor([TARGET_STD], dtype=torch.float32)
    return tn


def regime_entries(contact_wn, yt_wn, yh_wn):
    """Per-station R^2 binned by seabed-contact regime, as in evaluate() (patch 16).

    contact_wn: the raw 0/1 contact flag [W, N]; yt/yh: NORMALISED tension [W, N]
    (station R^2 is affine-invariant; the 1e-8 validity floor is in normalised units)."""
    _frac = contact_wn.float().mean(dim=0)
    _ssr = ((yh_wn - yt_wn) ** 2).sum(dim=0)
    _sst = ((yt_wn - yt_wn.mean(dim=0, keepdim=True)) ** 2).sum(dim=0)
    _r2n = 1.0 - _ssr / _sst.clamp_min(1e-8)
    out = []
    for fv, r2, ok in zip(_frac.tolist(), _r2n.tolist(), (_sst > 1e-8).tolist()):
        if not ok:
            continue
        out.append(("grounded" if fv >= 0.98 else "touchdown" if fv > 0.02 else "suspended", r2))
    return out


def _eval_task(task):
    """Predictions of every rung on the task's windows, and per-window results.

    Returns {key: {rung: (m, regime, dump)}}, key = (loc, case, N, start).

    The rungs are nested: one design (the widest blocks, the longest lag set, whose leading
    columns are every shorter lag set's) serves them all, each rung reading its leading
    columns. Weights are on standardised inputs: (mu, sd) by default, or the rung's own pair
    in task['stand'] (LR4 has its own standardiser, so LR0-LR3 stay exactly as before)."""
    cache, lc = task["cache_dir"], task["lc"]
    weights = {k: np.asarray(v) for k, v in task["weights"].items()}    # standardised, [1+p]
    mu, sd = np.asarray(task["mu"]), np.asarray(task["sd"])
    rungs = task["rungs"]
    r_lags = {r: tuple(task.get("rung_lags", {}).get(r, task.get("lags", LAGS))) for r in rungs}
    stand = {r: (np.asarray(m_), np.asarray(s_)) for r, (m_, s_) in task.get("stand", {}).items()}
    fitted = [r for r in rungs if r != "LR0_static"]
    lags = max((r_lags[r] for r in fitted), key=len) if fitted else LAGS
    assert all(lags[:len(r_lags[r])] == r_lags[r] for r in fitted), "lag sets are not nested"
    blocks = max((RUNGS[r] for r in rungs), key=len)     # the rungs are nested
    p_full = n_cols(blocks, lags)
    p_of = {r: n_cols(RUNGS[r], r_lags[r]) for r in fitted}
    p_def = max([p_of[r] for r in fitted if r not in stand], default=0)
    snap_times = task["snap_times"]
    mape_min = float(task["mape_min"])
    tn = _target_norm()
    out = {}
    for case, per_n in task["cases"]:
        arr = load_case(cache, lc, case)
        env_row = torch.tensor(arr["env"], dtype=torch.float32)
        evs = snap_times.get((lc, case), [])
        for nc, starts in per_n:
            graph = case_graph(arr, lc, case, nc)
            rec = resampled_record(arr, nc)
            step = _chunk(WINDOW_LEN, nc, p_full, budget_bytes=120e6, cap=8)
            for i in range(0, len(starts), step):
                st = torch.tensor(starts[i:i + step])
                idx = st[:, None] + torch.arange(WINDOW_LEN)[None]
                dyn = batched_dynamic_features(rec["x"][idx], rec["z"][idx], graph, env_row)
                X = design(graph, dyn, blocks, lags).numpy().astype(np.float64)   # [B,W,N,P]
                Z = (X[..., :p_def] - mu[:p_def]) / sd[:p_def]
                Zr = {r: (X[..., :p_of[r]] - m_[:p_of[r]]) / s_[:p_of[r]] for r, (m_, s_) in stand.items()}
                del X
                y_true = rec["T"][idx]                                              # [B,W,N]
                for j, s in enumerate(st.tolist()):
                    key = (lc, case, nc, int(s))
                    yt_n = tn.transform(y_true[j].unsqueeze(-1))                   # [W,N,1]
                    true_w = tn.inverse_transform(yt_n)[..., 0].numpy()
                    contact = dyn[j, :, :, CONTACT_FLAG_IDX]
                    ev_rows = [int(t) - int(s) for t in evs if int(s) <= int(t) < int(s) + WINDOW_LEN]
                    res = {}
                    for rung in rungs:
                        if rung == "LR0_static":
                            pred = static_prediction(graph, WINDOW_LEN).double()
                        else:
                            p = p_of[rung]
                            wv = weights[rung]
                            zz = Zr[rung] if rung in Zr else Z
                            pred = torch.from_numpy(wv[0] + zz[j, :, :, :p] @ wv[1:])
                        yh_n = tn.transform(pred.float().unsqueeze(-1))
                        m = S1.compute_physical_metrics_per_target(
                            y_hat_norm=yh_n, y_true_norm=yt_n, target_norm=tn,
                            target_names=["tension"], mape_min=mape_min)
                        reg = regime_entries(contact, yt_n[..., 0], yh_n[..., 0])
                        pred_w = tn.inverse_transform(yh_n)[..., 0].numpy()
                        res[rung] = (m, reg, _dump_row(true_w, pred_w, ev_rows, key))
                    out[key] = res
    return out


def _dump_row(true_w, pred_w, ev_rows, key):
    """Per-window scalars of the Stage-1 test dump (cell pubts01, patches 23/27/sr-20)."""
    lc, case, nc, s = key
    snaps = []
    for r in ev_rows:
        n_st = int(true_w.shape[1])
        tt = np.full((len(SNAP_NBHD_OFF), SNAP_NBHD_MAXN), np.nan, np.float32)
        pp = np.full((len(SNAP_NBHD_OFF), SNAP_NBHD_MAXN), np.nan, np.float32)
        for j, o in enumerate(SNAP_NBHD_OFF):
            if 0 <= r + o < int(true_w.shape[0]):
                tt[j, :n_st] = true_w[r + o]
                pp[j, :n_st] = pred_w[r + o]
        snaps.append(((lc, case, nc, s, s + r), float(true_w[r].max()), float(pred_w[r].max()),
                      tt, pp, n_st))
    return dict(fl_true=float(true_w[:, -1].max()), fl_pred=float(pred_w[:, -1].max()),
                lp_true=float(true_w.max()), lp_pred=float(pred_w.max()), snaps=snaps)


def run_task(task):
    if task["kind"] in ("moments", "fit"):
        return _fit_task(task)
    if task["kind"] == "eval":
        return _eval_task(task)
    raise ValueError(task["kind"])


def _tree_rss_gb():
    try:
        import psutil
        p = psutil.Process(os.getpid())
        return (p.memory_info().rss + sum(c.memory_info().rss for c in p.children(recursive=True))) / 1e9
    except Exception:
        return float("nan")


def _avail_gb():
    try:
        import psutil
        return psutil.virtual_memory().available / 1e9
    except Exception:
        return float("nan")


def _memory_check(label, rss_limit_gb, min_avail_gb):
    """Raise MemoryError before the machine runs short. The free-memory floor matters on
    Windows, which trims working sets under pressure, so RSS alone under-reports."""
    rss = _tree_rss_gb()
    if rss == rss and rss > rss_limit_gb:
        raise MemoryError(f"[{label}] process-tree RSS {rss:.1f} GB > {rss_limit_gb:.1f} GB")
    if min_avail_gb > 0:
        av = _avail_gb()
        if av == av and av < min_avail_gb:
            raise MemoryError(f"[{label}] free memory {av:.1f} GB < {min_avail_gb:.1f} GB; "
                              f"rerun with fewer workers (LR_WORKERS)")
    return rss


def run_parallel(tasks, n_workers, label, cache_dir=None, rss_limit_gb=None, min_avail_gb=None,
                 every=None):
    """Run tasks (in a process pool if n_workers > 1) and return results in TASK order.

    With cache_dir, each finished fit/moments task is saved as <tid>.npz and reused on a
    rerun, so an interrupted pass resumes. Results never depend on completion order.
    Memory is checked after every task (module settings RSS_LIMIT_GB / MIN_AVAIL_GB); on a
    breach, or any error, queued tasks are dropped and the workers are stopped at once."""
    rss_limit_gb = RSS_LIMIT_GB if rss_limit_gb is None else rss_limit_gb
    min_avail_gb = MIN_AVAIL_GB if min_avail_gb is None else min_avail_gb
    results = [None] * len(tasks)
    todo = []
    for i, t in enumerate(tasks):
        f = None if cache_dir is None else Path(cache_dir) / f"{t['tid']}.npz"
        if f is not None and f.exists():
            with np.load(f) as z:
                results[i] = {k: z[k] for k in z.files}
        else:
            todo.append(i)
    if len(todo) < len(tasks):
        print(f"[{label}] {len(tasks) - len(todo)} of {len(tasks)} tasks reused from {cache_dir}")
    if not todo:
        return results
    every = every or max(1, len(todo) // 40)
    t0, done = time.time(), 0

    def _store(i, res):
        nonlocal done
        results[i] = res
        if cache_dir is not None:
            Path(cache_dir).mkdir(parents=True, exist_ok=True)
            np.savez(Path(cache_dir) / f"{tasks[i]['tid']}.npz", **res)
        done += 1
        rss = _memory_check(label, rss_limit_gb, min_avail_gb)
        if done % every == 0 or done == len(todo):
            el = time.time() - t0
            eta = el / done * (len(todo) - done)
            print(f"[{label}] {done}/{len(todo)} tasks | {el / 60:5.1f} min elapsed | "
                  f"ETA {eta / 60:5.1f} min | RSS {rss:.1f} GB", flush=True)

    if n_workers <= 1:
        worker_init(max(1, torch.get_num_threads()))
        for i in todo:
            _store(i, run_task(tasks[i]))
        return results

    import multiprocessing as mp
    from concurrent.futures import ProcessPoolExecutor, as_completed
    # 'spawn' on every platform: the start method this code was validated with (Windows has no
    # other), and it never forks a Jupyter kernel that is running threads.
    ex = ProcessPoolExecutor(max_workers=min(int(n_workers), len(todo)),
                             mp_context=mp.get_context("spawn"), initializer=worker_init)
    try:
        fut = {ex.submit(run_task, tasks[i]): i for i in todo}
        for f in as_completed(fut):
            _store(fut[f], f.result())
    except BaseException:
        # The default shutdown would first run every queued task; stop now instead. The worker
        # list is taken first: shutdown() drops the executor's reference to it.
        procs = list((getattr(ex, "_processes", None) or {}).values())
        ex.shutdown(wait=False, cancel_futures=True)
        for proc in procs:
            proc.terminate()
        raise
    ex.shutdown(wait=True)
    return results


# ----------------------------------------------------------------------------- solve
def moments_to_standardiser(results):
    s1 = sum(r["s1"] for r in results)
    s2 = sum(r["s2"] for r in results)
    n = float(sum(r["n"] for r in results))
    mu = s1 / n
    sd = np.sqrt(np.maximum(s2 / n - mu * mu, 0.0))
    const = sd < (np.abs(mu) + 1.0) * 1e-6     # guard_constant_columns (FeatureStandardizer)
    sd = np.where(const, 1.0, sd)
    return mu, sd, const


def combine_factors(results, group=None):
    """Merge the tasks' factors (QR of the stacked factors), in task order.

    group=None merges both halves of a two-group pass."""
    Rs, n = [], 0.0
    for r in results:
        sel = range(r["R"].shape[0]) if group is None else (group,)
        for g in sel:
            Rs.append(r["R"][g])
            n += float(r["n"][g])
    R = np.linalg.qr(np.vstack(Rs), mode="r")
    return dict(R=_square(R, Rs[0].shape[1]), n=n)


def merge_factors(*facs):
    """One factor from several (e.g. the two halves of a pass): QR of the stacked factors."""
    q = facs[0]["R"].shape[1]
    R = np.linalg.qr(np.vstack([f["R"] for f in facs]), mode="r")
    return dict(R=_square(R, q), n=float(sum(f["n"] for f in facs)))


def excluded_inputs(names=None):
    """Indices (into the input columns) of the exact duplicates, removed before solving."""
    names = column_names() if names is None else names
    return sorted(names.index(n) for n in EXACT_DUPLICATES)


def ls_solve(fac, k, ridge=0.0, rcond=1e-12, exclude=()):
    """Least-squares weights [intercept, k inputs] from a factor of [1, z_1..z_p, y].

    Uses the leading k input columns (LR1 lies inside LR2 inside LR3) minus `exclude`, whose
    weights are returned as zero. Solved with numpy.linalg.lstsq on the small system
    R[:, cols] w = R[:, -1] (exact, since ||Z w - y|| = ||R [w; -1]||), whose singular values
    are those of the data themselves, not squared. The relative cutoff rcond gives any
    remaining exact collinearity (e.g. a column constant over the training set) the
    minimum-norm weights; the FITTED VALUES are the unique least-squares fit. ridge > 0 adds
    lambda * n * |w_inputs|^2 (lambda in units of the standardised variance; the intercept is
    not penalised)."""
    R, n = fac["R"], fac["n"]
    ex = set(int(j) for j in exclude)
    cols = [0] + [j + 1 for j in range(k) if j not in ex]
    A = R[:, cols]
    c = R[:, -1]
    if ridge:
        E = np.zeros((len(cols) - 1, len(cols)))
        E[:, 1:] = math.sqrt(ridge * n) * np.eye(len(cols) - 1)
        A = np.vstack([A, E])
        c = np.concatenate([c, np.zeros(len(cols) - 1)])
    w_s, _res, rank, sv = np.linalg.lstsq(A, c, rcond=rcond)
    w = np.zeros(k + 1)
    w[cols] = w_s
    kept = sv[sv > rcond * sv.max()]
    return w, dict(size=len(cols), rank=int(rank), cond=float(sv.max() / kept.min()),
                   ridge=float(ridge))


def fit_stats(w, fac):
    """MSE, RMSE and R^2 of weights w on the rows a factor was built from (exact:
    ||Z w - y||^2 = ||R [w; 0; -1]||^2 because Q has orthonormal columns)."""
    R, n = fac["R"], fac["n"]
    k = w.size - 1
    r = R[:, :k + 1] @ w - R[:, -1]
    sse = float(r @ r)
    sst = float(np.sum(R[1:, -1] ** 2))     # residual of the intercept-only fit
    return dict(mse=sse / n, rmse=math.sqrt(sse / n), r2=1.0 - sse / sst, n=n)


def static_weights(mu, sd, k):
    """LR0 (T = tension0) written as fixed linear weights, so fit_stats can score it."""
    w = np.zeros(k + 1)
    j = STATIC_NAMES.index("tension0")
    w[0], w[1 + j] = mu[j], sd[j]
    return w


def raw_coefficients(w, mu, sd):
    """Weights in physical input units: T = c0 + sum_j c_j x_j."""
    p = w.size - 1
    c = w[1:] / sd[:p]
    return float(w[0] - np.sum(c * mu[:p])), c


def restandardise(w, mu, sd, mu_new, sd_new):
    """The same linear model, written on inputs standardised with (mu_new, sd_new)."""
    p = w.size - 1
    c0, c = raw_coefficients(w, mu, sd)
    out = np.empty(p + 1)
    out[0] = c0 + float(np.sum(c * mu_new[:p]))
    out[1:] = c * sd_new[:p]
    return out


# ----------------------------------------------------------------------------- materialise
def materialise(cache_dir, keys, blocks, lags=LAGS):
    """Raw design rows and targets of a few windows (for the scikit-learn check)."""
    Xs, ys = [], []
    for (lc, case), per_n in _by_case(keys).items():
        arr = load_case(cache_dir, lc, case)
        env_row = torch.tensor(arr["env"], dtype=torch.float32)
        for nc, starts in per_n.items():
            graph = case_graph(arr, lc, case, nc)
            rec = resampled_record(arr, nc)
            st = torch.tensor(starts)
            idx = st[:, None] + torch.arange(WINDOW_LEN)[None]
            dyn = batched_dynamic_features(rec["x"][idx], rec["z"][idx], graph, env_row)
            Xs.append(design(graph, dyn, blocks, lags).reshape(-1, n_cols(blocks, lags))
                      .numpy().astype(np.float64))
            ys.append(rec["T"][idx].reshape(-1).numpy().astype(np.float64))
    return np.concatenate(Xs), np.concatenate(ys)


def predict_windows(cache_dir, keys, weights, mu, sd, lags=LAGS, stand=None):
    """{key: {'true': [W,N], rung: [W,N]}} for a handful of windows (figures).

    lags: the longest lag set among the rungs (its leading columns serve the shorter ones);
    stand: {rung: (mu, sd)} for a rung with its own standardiser (LR4)."""
    out = {}
    stand = stand or {}
    tn = _target_norm()
    for (lc, case), per_n in _by_case(keys).items():
        arr = load_case(cache_dir, lc, case)
        env_row = torch.tensor(arr["env"], dtype=torch.float32)
        for nc, starts in per_n.items():
            graph = case_graph(arr, lc, case, nc)
            rec = resampled_record(arr, nc)
            for s in starts:
                idx = (torch.tensor([s])[:, None] + torch.arange(WINDOW_LEN)[None])
                dyn = batched_dynamic_features(rec["x"][idx], rec["z"][idx], graph, env_row)
                X = design(graph, dyn, FULL_BLOCKS, lags)[0].numpy().astype(np.float64)
                d = {"true": tn.inverse_transform(tn.transform(rec["T"][idx][0].unsqueeze(-1)))[..., 0].numpy(),
                     "LR0_static": static_prediction(graph, WINDOW_LEN).numpy().copy()}
                for rung, wv in weights.items():
                    p = wv.size - 1
                    m_, s_ = stand.get(rung, (mu, sd))
                    Z = (X[..., :p] - m_[:p]) / s_[:p]
                    d[rung] = (wv[0] + Z @ wv[1:]).astype(np.float32)
                out[(lc, case, nc, int(s))] = d
    return out


# ----------------------------------------------------------------------------- gates
def check_features(cache_dir, keys):
    """GATE 2: batched features and targets vs MooringSequenceDatasetPositionTension itself.

    Returns (windows checked, max |x_seq difference|, max |y_seq difference|)."""
    mx = my = 0.0
    n = 0
    for (lc, case), per_n in _by_case(keys).items():
        arr = load_case(cache_dir, lc, case)
        env_row = torch.tensor(arr["env"], dtype=torch.float32)
        for nc, starts in per_n.items():
            graph = case_graph(arr, lc, case, nc)
            rec = resampled_record(arr, nc)
            ds = S1.MooringSequenceDatasetPositionTension(graph, case_dir(cache_dir, lc, case), nc,
                                                          WINDOW_LEN)
            st = torch.tensor(starts)
            idx = st[:, None] + torch.arange(WINDOW_LEN)[None]
            dyn = batched_dynamic_features(rec["x"][idx], rec["z"][idx], graph, env_row)
            for j, s in enumerate(starts):
                item = ds[s]
                mx = max(mx, float((dyn[j] - item["x_seq"]).abs().max()))
                my = max(my, float((rec["T"][idx][j] - item["y_seq"][..., 0]).abs().max()))
                n += 1
    return n, mx, my


def check_ols_vs_reference(cache_dir, keys, mu, sd, blocks=("own", "ctx"), exclude=(), lags=LAGS):
    """GATE 3: the streamed least-squares path (standardise, QR-accumulate, solve) against an
    independent least-squares solve on the same materialised rows: scikit-learn's
    LinearRegression when it is installed, otherwise the algorithm it runs, in numpy (centre
    the inputs and the target, then an SVD-based least-squares solve).

    Coefficients are not unique when inputs are collinear, so the FITTED VALUES are compared.

    The reference scales each input by its own standard deviation over these rows (as a
    StandardScaler would), independently of (mu, sd). Without the scaling, a relative singular-
    value cutoff applied to raw inputs whose units span six orders of magnitude (positions, drag
    forces in N, penetration depths) drops genuine directions of the small-unit columns: on LR4's
    1,618 inputs this made the raw-input reference a WORSE least-squares fit than ours (job 882173:
    max difference 1.2e-3 of std(y), reference RMSE 19.9188 N against ours 19.9175 N); scaled, the
    two agree to 2.6e-8.
    Returns (rows, max |difference| / std(y), name of the reference)."""
    X, y = materialise(cache_dir, keys, blocks, lags)
    p = X.shape[1]
    M = np.empty((X.shape[0], p + 2))
    M[:, 0] = 1.0
    M[:, 1:p + 1] = (X - mu[:p]) / sd[:p]
    M[:, -1] = y
    fac = dict(R=_square(_qr_update(None, M), p + 2), n=float(y.size))
    w, _ = ls_solve(fac, p, exclude=exclude)
    ours = M[:, :p + 1] @ w
    del M
    Xk = X[:, [j for j in range(p) if j not in set(exclude)]]
    del X
    xm, xs = Xk.mean(axis=0), Xk.std(axis=0)
    Xs = (Xk - xm) / np.where(xs > 0.0, xs, 1.0)       # the reference's own scaling
    del Xk
    try:
        from sklearn.linear_model import LinearRegression
        ref = LinearRegression().fit(Xs, y).predict(Xs)
        name = "scikit-learn's LinearRegression on standardised inputs"
    except ImportError:
        ym = y.mean()
        coef = np.linalg.lstsq(Xs, y - ym, rcond=None)[0]
        ref = Xs @ coef + ym
        name = "numpy lstsq on standardised, centred inputs (scikit-learn's algorithm)"
    return int(y.size), float(np.max(np.abs(ours - ref)) / np.std(y)), name


# ----------------------------------------------------------------------------- aggregation
PW_FIELDS = ['lc_id', 'case_id', 'n_in', 'out_N', 'start_idx', 'n_pts', 'ss_res', 'y_sum', 'y_sq',
             'mae', 'rmse', 'r2', 'mape', 'mape_valid_frac', 'td_mae', 'td_mae_flat', 'td_skill',
             'peak_MAE', 'peak_bias']


class EvalAccumulator:
    """The aggregation of evaluate() (cell 8f268a8b), fed one window at a time.

    The loop body and the tail of evaluate() are reproduced statement for statement; only the
    model call, the Kendall loss and the data loader are gone (a linear model has no loss to
    report and its windows arrive from the worker pool)."""

    def __init__(self, target_names=("tension",)):
        from collections import defaultdict as _dd
        self.target_names = list(target_names)
        tn = self.target_names
        self.num_windows = 0
        self.struct_sums = {
            "MAE": {n: 0.0 for n in tn}, "RMSE": {n: 0.0 for n in tn}, "R2": {n: 0.0 for n in tn},
            "ss_res": {n: 0.0 for n in tn}, "y_sum": {n: 0.0 for n in tn},
            "y_sq": {n: 0.0 for n in tn}, "n_pts": {n: 0.0 for n in tn},
        }
        self.flat_sums, self.flat_counts = {}, {}
        self.all_peak_abs_errors, self.all_peak_true_peaks, self.all_peak_signed_errors = [], [], []
        self._regime_r2 = {"grounded": [], "touchdown": [], "suspended": []}
        self.nc_struct = _dd(lambda: {k: {n: 0.0 for n in tn}
                                      for k in ("MAE", "RMSE", "R2", "ss_res", "y_sum", "y_sq", "n_pts")})
        self.nc_flat, self.nc_flat_c = _dd(dict), _dd(dict)
        self.nc_peak_abs, self.nc_peak_true, self.nc_peak_signed = _dd(list), _dd(list), _dd(list)
        self.nc_nb = _dd(int)
        self.per_window_rows = []

    def add(self, m, regime, key):
        import math as _math
        lc, case, nc_val, start = key
        target_names = self.target_names
        self.num_windows += 1
        for rg, r2 in regime:
            self._regime_r2[rg].append(r2)
        for metric in ("MAE", "RMSE", "R2"):
            for n in target_names:
                self.struct_sums[metric][n] += m[metric][n]
        for rk in ("ss_res", "y_sum", "y_sq"):
            for n in target_names:
                self.struct_sums[rk][n] += m[rk][n]
        for n in target_names:
            self.struct_sums["n_pts"][n] += m["n_pts"]
        self.all_peak_abs_errors.extend(m.get("peak_tension_abs_errors", []))
        self.all_peak_true_peaks.extend(m.get("peak_tension_true_peaks", []))
        self.all_peak_signed_errors.extend(m.get("peak_tension_signed_errors", []))

        _pwn = target_names[0]
        self.per_window_rows.append({
            "lc_id": lc, "case_id": case, "n_in": nc_val, "out_N": nc_val, "start_idx": start,
            "n_pts": m["n_pts"], "ss_res": m["ss_res"][_pwn], "y_sum": m["y_sum"][_pwn],
            "y_sq": m["y_sq"][_pwn], "mae": m["MAE"][_pwn], "rmse": m["RMSE"][_pwn],
            "r2": m["R2"][_pwn],
            "mape": m["MAPE"].get(_pwn, float("nan")),
            "mape_valid_frac": m["MAPE"].get(_pwn + "_valid_frac", float("nan")),
            "td_mae": m.get("temporal_diff_MAE_" + _pwn, float("nan")),
            "td_mae_flat": m.get("temporal_diff_MAE_flat_" + _pwn, float("nan")),
            "td_skill": m.get("temporal_diff_skill_" + _pwn, float("nan")),
            "peak_MAE": m.get("peak_tension_MAE", float("nan")),
            "peak_bias": m.get("peak_tension_bias", float("nan")),
        })

        _skip = {"MAE", "RMSE", "R2", "MAPE", "ss_res", "y_sum", "y_sq",
                 "n_pts", "peak_tension_abs_errors", "peak_tension_true_peaks", "peak_tension_signed_errors"}
        flat_keys = list(m["MAPE"].keys()) + [k for k in m if k not in _skip]
        for k in flat_keys:
            val = m["MAPE"].get(k) if k in m["MAPE"] else m[k]
            if k not in self.flat_sums:
                self.flat_sums[k] = 0.0
                self.flat_counts[k] = 0
            if not _math.isnan(val):
                self.flat_sums[k] += val
                self.flat_counts[k] += 1

        self.nc_nb[nc_val] += 1
        for metric in ("MAE", "RMSE", "R2"):
            for n in target_names:
                self.nc_struct[nc_val][metric][n] += m[metric][n]
        for rk in ("ss_res", "y_sum", "y_sq"):
            for n in target_names:
                self.nc_struct[nc_val][rk][n] += m[rk][n]
        for n in target_names:
            self.nc_struct[nc_val]["n_pts"][n] += m["n_pts"]
        self.nc_peak_abs[nc_val].extend(m.get("peak_tension_abs_errors", []))
        self.nc_peak_true[nc_val].extend(m.get("peak_tension_true_peaks", []))
        self.nc_peak_signed[nc_val].extend(m.get("peak_tension_signed_errors", []))
        for k in flat_keys:
            val = m["MAPE"].get(k) if k in m["MAPE"] else m[k]
            if k not in self.nc_flat[nc_val]:
                self.nc_flat[nc_val][k] = 0.0
                self.nc_flat_c[nc_val][k] = 0
            if not _math.isnan(val):
                self.nc_flat[nc_val][k] += val
                self.nc_flat_c[nc_val][k] += 1

    def finalize(self):
        target_names = self.target_names
        _meps = 1e-8

        def _global_r2(ss_d, ys_d, yq_d, np_d, tnames):
            out = {}
            for n in tnames:
                n_t = np_d[n]
                if n_t < 2:
                    out[n] = float("nan"); continue
                gm = ys_d[n] / n_t
                ss_tot = yq_d[n] - n_t * gm ** 2
                out[n] = float(1.0 - ss_d[n] / max(ss_tot, _meps))
            return out

        def _agg_p95_max(errs):
            if not errs:
                return float("nan"), float("nan")
            se = sorted(errs)
            return float(se[max(0, int(0.95 * len(se)) - 1)]), float(se[-1])

        def _peak_tail_stats(true_pk, signed_err, q):
            if not true_pk:
                return (float("nan"),) * 5
            pairs = sorted(zip(true_pk, signed_err), key=lambda t: t[0])
            k = max(1, int(round((1.0 - q) * len(pairs))))
            tail = pairs[len(pairs) - k:]
            thr = float(tail[0][0])
            errs = [e for _t, e in tail]
            under = 100.0 * sum(1 for e in errs if e < 0) / len(errs)
            bias = float(sum(errs) / len(errs))
            mae = float(sum(abs(e) for e in errs) / len(errs))
            _neg = [abs(e) for e in errs if e < 0]
            undermag = float(sum(_neg) / len(_neg)) if _neg else 0.0
            return thr, under, bias, mae, undermag

        def _build_avg(struct_s, flat_s, flat_c, nb, pk_list):
            avg = {
                "MAE": {n: struct_s["MAE"][n] / max(1, nb) for n in target_names},
                "RMSE": {n: struct_s["RMSE"][n] / max(1, nb) for n in target_names},
                "R2": {n: struct_s["R2"][n] / max(1, nb) for n in target_names},
                "global_R2": _global_r2(struct_s["ss_res"], struct_s["y_sum"], struct_s["y_sq"],
                                        struct_s["n_pts"], target_names),
                "MAPE": {},
            }
            for k, s in flat_s.items():
                cnt = flat_c[k]
                val = s / cnt if cnt > 0 else float("nan")
                if k in ("tension", "tension_valid_frac"):
                    avg["MAPE"][k] = val
                else:
                    avg[k] = val
            p95, pmax = _agg_p95_max(pk_list)
            avg["peak_tension_p95_abs_error"] = p95
            avg["peak_tension_max_abs_error"] = pmax
            return avg

        avg_metrics = _build_avg(self.struct_sums, self.flat_sums, self.flat_counts,
                                 self.num_windows, self.all_peak_abs_errors)
        for _q, _tag in ((0.90, "p90"), (0.99, "p99")):
            _thr, _und, _bias, _mae, _umag = _peak_tail_stats(
                self.all_peak_true_peaks, self.all_peak_signed_errors, _q)
            avg_metrics[f"peak_tension_thr_{_tag}"] = _thr
            avg_metrics[f"peak_tension_underpred_rate_{_tag}"] = _und
            avg_metrics[f"peak_tension_bias_{_tag}"] = _bias
            avg_metrics[f"peak_tension_MAE_{_tag}"] = _mae
            avg_metrics[f"peak_tension_undermag_{_tag}"] = _umag
        for _rg in ("grounded", "touchdown", "suspended"):
            _vals = self._regime_r2[_rg]
            if _vals:
                avg_metrics[f"contact_{_rg}_R2_median"] = float(statistics.median(_vals))
                avg_metrics[f"contact_{_rg}_R2_fracneg"] = float(
                    100.0 * sum(1 for v in _vals if v < 0) / len(_vals))
                avg_metrics[f"contact_{_rg}_n"] = len(_vals)
            else:
                avg_metrics[f"contact_{_rg}_R2_median"] = float("nan")
                avg_metrics[f"contact_{_rg}_R2_fracneg"] = float("nan")
                avg_metrics[f"contact_{_rg}_n"] = 0
        per_nc = {}
        for nc_key, nb_val in self.nc_nb.items():
            _m_nc = _build_avg(self.nc_struct[nc_key], self.nc_flat[nc_key],
                               self.nc_flat_c[nc_key], nb_val, self.nc_peak_abs[nc_key])
            for _q, _tag in ((0.90, "p90"), (0.99, "p99")):
                _t, _u, _b, _ma, _um = _peak_tail_stats(
                    self.nc_peak_true[nc_key], self.nc_peak_signed[nc_key], _q)
                _m_nc[f"peak_tension_thr_{_tag}"] = _t
                _m_nc[f"peak_tension_underpred_rate_{_tag}"] = _u
                _m_nc[f"peak_tension_bias_{_tag}"] = _b
                _m_nc[f"peak_tension_MAE_{_tag}"] = _ma
                _m_nc[f"peak_tension_undermag_{_tag}"] = _um
            per_nc[nc_key] = _m_nc
        return avg_metrics, per_nc


_TAIL_KEYS = ("peak_tension_MAE", "peak_tension_RMSE", "peak_tension_bias",
              "peak_tension_underpred_rate", "peak_tension_MAPE",
              "peak_tension_p95_abs_error", "peak_tension_max_abs_error",
              "peak_tension_thr_p90", "peak_tension_underpred_rate_p90",
              "peak_tension_bias_p90", "peak_tension_MAE_p90",
              "peak_tension_thr_p99", "peak_tension_underpred_rate_p99",
              "peak_tension_bias_p99", "peak_tension_MAE_p99",
              "peak_tension_undermag_p90", "peak_tension_undermag_p99")
NC_FIELDS = [
    "split", "node_count",
    "MAE_tension", "RMSE_tension", "R2_tension", "global_R2_tension", "MAPE_tension",
    "peak_tension_MAE", "peak_tension_bias", "peak_tension_underpred_rate", "peak_tension_MAPE",
    "peak_tension_p95_abs_error", "peak_tension_max_abs_error",
    "peak_tension_thr_p90", "peak_tension_underpred_rate_p90",
    "peak_tension_bias_p90", "peak_tension_MAE_p90", "peak_tension_undermag_p90",
    "peak_tension_thr_p99", "peak_tension_underpred_rate_p99",
    "peak_tension_bias_p99", "peak_tension_MAE_p99", "peak_tension_undermag_p99",
    "temporal_diff_MAE_tension", "temporal_diff_MAE_flat_tension", "temporal_diff_skill_tension",
]


def write_test_outputs(out_dir, test_metrics, per_nc, pw_rows, target_names=("tension",)):
    """The three CSVs of test_model() (cell d75ee9f2), same file names and columns.

    test_loss is left empty: it is the Kendall objective of the neural model and a linear
    regression has none."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    _tn = list(target_names)
    _g = test_metrics.get("global_R2", {})
    _rows = [("test_loss", "")]
    for _n in _tn: _rows.append((f"test_MAE_{_n}", test_metrics["MAE"].get(_n, "")))
    for _n in _tn: _rows.append((f"test_RMSE_{_n}", test_metrics["RMSE"].get(_n, "")))
    for _n in _tn: _rows.append((f"test_R2_{_n}", test_metrics["R2"].get(_n, "")))
    for _n in _tn: _rows.append((f"test_global_R2_{_n}", _g.get(_n, "")))
    _rows.append(("test_MAPE_tension", test_metrics["MAPE"].get("tension", "")))
    _rows.append(("test_MAPE_tension_valid_frac", test_metrics["MAPE"].get("tension_valid_frac", "")))
    for _k in _TAIL_KEYS:
        _rows.append((f"test_{_k}", test_metrics.get(_k, "")))
    for _rg in ("grounded", "touchdown", "suspended"):
        for _sfx in ("R2_median", "R2_fracneg", "n"):
            _rows.append((f"test_contact_{_rg}_{_sfx}", test_metrics.get(f"contact_{_rg}_{_sfx}", "")))
    for _n in _tn:
        _rows.append((f"test_temporal_diff_MAE_{_n}", test_metrics.get(f"temporal_diff_MAE_{_n}", "")))
        _rows.append((f"test_temporal_diff_MAE_flat_{_n}", test_metrics.get(f"temporal_diff_MAE_flat_{_n}", "")))
        _rows.append((f"test_temporal_diff_skill_{_n}", test_metrics.get(f"temporal_diff_skill_{_n}", "")))

    with open(out_dir / "test_per_window_stats.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=PW_FIELDS, extrasaction="ignore")
        w.writeheader()
        w.writerows(pw_rows)
    with open(out_dir / "test_metrics.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["metric", "value"])
        w.writerows(_rows)
    with open(out_dir / "test_metrics_by_node_count.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=NC_FIELDS, extrasaction="ignore")
        w.writeheader()
        for k in sorted(per_nc):
            m = per_nc[k]
            row = {"split": "test", "node_count": k,
                   "MAE_tension": m["MAE"].get("tension", ""), "RMSE_tension": m["RMSE"].get("tension", ""),
                   "R2_tension": m["R2"].get("tension", ""),
                   "global_R2_tension": m["global_R2"].get("tension", ""),
                   "MAPE_tension": m["MAPE"].get("tension", "")}
            for c in NC_FIELDS[7:]:
                row[c] = m.get(c, "")
            w.writerow(row)


def write_dump(path, dump_rows, fig_traces=None):
    """The scalar part of the Stage-1 test dump, same keys, plus figure traces."""
    meta, pt, pp, lt, lp = [], [], [], [], []
    sev, strue, spred, snt, snp, snout = [], [], [], [], [], []
    for key, d in dump_rows:
        meta.append(key)
        pt.append(d["fl_true"]); pp.append(d["fl_pred"])
        lt.append(d["lp_true"]); lp.append(d["lp_pred"])
        for ev, a, b, tt, ppn, nst in d["snaps"]:
            sev.append(ev); strue.append(a); spred.append(b)
            snt.append(tt); snp.append(ppn); snout.append(nst)
    arrays = dict(
        peak_true_all=np.asarray(pt, np.float64), peak_pred_all=np.asarray(pp, np.float64),
        meta_all=np.asarray(meta, np.int32).reshape(-1, 4),
        lpeak_true_all=np.asarray(lt, np.float64), lpeak_pred_all=np.asarray(lp, np.float64),
        snap_ev=np.asarray(sev, np.int32).reshape(-1, 5),
        snap_true=np.asarray(strue, np.float64), snap_pred=np.asarray(spred, np.float64),
        snap_nbhd_true=(np.stack(snt) if snt else np.zeros((0, len(SNAP_NBHD_OFF), SNAP_NBHD_MAXN), np.float32)),
        snap_nbhd_pred=(np.stack(snp) if snp else np.zeros((0, len(SNAP_NBHD_OFF), SNAP_NBHD_MAXN), np.float32)),
        snap_nbhd_offsets=np.asarray(SNAP_NBHD_OFF, np.int32),
        snap_row_nout=np.asarray(snout, np.int32),
        dt=np.float64(S1.FEATURE_DT), node_counts=np.asarray(LAYOUTS, np.int32))
    for name, tr in (fig_traces or {}).items():
        arrays[f"{name}_true"] = tr["true"]
        arrays[f"{name}_pred"] = tr["pred"]
        arrays[f"{name}_meta"] = np.asarray(tr["meta"], np.int32)
    np.savez(path, **arrays)


# ----------------------------------------------------------------------------- comparison
def kv(path):
    with open(path, newline="", encoding="utf-8") as f:
        r = csv.reader(f)
        next(r)
        return {a: b for a, b in r}


def read_rows(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def undermass(mae, bias):
    """Expected shortfall per tail entry, (MAE - bias) / 2 (Method, eq. metrics_tail)."""
    return (mae - bias) / 2.0


def site_peak_stats(z, sites):
    """Fairlead-peak median ratio, mean relative error [%] and underprediction rate [%]."""
    meta, t, p = z["meta_all"], z["peak_true_all"], z["peak_pred_all"]
    sel = np.isin(meta[:, 0], sites)
    e = p[sel] - t[sel]
    return dict(ratio=float(np.median(p[sel] / t[sel])),
                relerr=100.0 * float(np.mean(np.abs(e) / t[sel])),
                up=100.0 * float((e < 0).mean()), n=int(sel.sum()))


def tail_split(z):
    """Fairlead-peak tail split by snap membership, p90 and p99 of TRUE peak (paperA_numbers)."""
    meta, pt, pp = z["meta_all"], z["peak_true_all"], z["peak_pred_all"]
    keys = {(int(a), int(b), int(c), int(d)) for a, b, c, d, _t in z["snap_ev"]}
    is_snap = np.array([(int(m[0]), int(m[1]), int(m[2]), int(m[3])) in keys for m in meta])
    e = pp - pt
    out = {}
    for q in (90, 99):
        thr = float(np.quantile(pt, q / 100.0))
        tail = pt >= thr
        for pop, mask in (("all", tail), ("nonsnap", tail & ~is_snap), ("snap", tail & is_snap)):
            s = e[mask]
            if s.size == 0:
                out[(q, pop)] = dict(thr=thr, n=0, share=0.0, up=float("nan"),
                                     bias=float("nan"), um=float("nan"))
                continue
            out[(q, pop)] = dict(thr=thr, n=int(mask.sum()), share=100.0 * mask.sum() / tail.sum(),
                                 up=100.0 * float((s < 0).mean()), bias=float(s.mean()),
                                 um=undermass(float(np.abs(s).mean()), float(s.mean())))
    return out


def snap_events(z):
    """{(loc, case, t): (median true, median pred, median of per-row pred/true)} (paperA_numbers)."""
    g = collections.defaultdict(list)
    for (lc, case, _nin, _s, t), a, b in zip(z["snap_ev"].tolist(), z["snap_true"], z["snap_pred"]):
        if a <= 0:
            continue
        g[(int(lc), int(case), int(t))].append((float(a), float(b)))
    return {k: (statistics.median(x for x, _ in v), statistics.median(y for _, y in v),
                statistics.median(y / x for x, y in v)) for k, v in g.items()}


def capture_summary(caps):
    a = np.asarray(caps, dtype=float)
    if a.size == 0:
        return dict(n=0, median=float("nan"), iqr=float("nan"), atleast=float("nan"))
    q1, q3 = np.quantile(a, [0.25, 0.75])
    return dict(n=int(a.size), median=float(np.median(a)), iqr=float(q3 - q1),
                atleast=100.0 * float(np.mean(a >= 1.0)))


def own_station_events(z, snap_node):
    """Snap capture at the snap's own station, per distinct event (paperA_numbers)."""
    offs = [int(o) for o in z["snap_nbhd_offsets"]]
    i0 = offs.index(0)
    g = collections.defaultdict(list)
    for k, (lc, case, _nin, _s, t) in enumerate(z["snap_ev"].tolist()):
        nout = int(z["snap_row_nout"][k])
        x = snap_node[(lc, case, t)] * (nout - 1) / 20.0
        if abs(x - round(x)) > 1e-9:
            continue
        i = int(round(x))
        tt, pp = z["snap_nbhd_true"][k, :, i], z["snap_nbhd_pred"][k, :, i]
        if not tt[i0] > 0:
            continue
        g[(lc, case, t)].append((float(pp[i0] / tt[i0]), float(np.nanmax(pp) / np.nanmax(tt)),
                                 float(z["snap_pred"][k] / z["snap_true"][k])))
    return {key: tuple(statistics.median(v[j] for v in vals) for j in range(3))
            for key, vals in g.items()}


def summarise_run(run_dir, snap_node):
    """One row of the comparison table for a model's output directory (screened draw)."""
    run_dir = Path(run_dir)
    p = {k: float(v) for k, v in kv(run_dir / "test_metrics.csv").items() if v not in ("",)}
    z = np.load(run_dir / "test_timeseries_dump.npz")
    ts = tail_split(z)
    ev = snap_events(z)
    own = own_station_events(z, snap_node)
    dev = site_peak_stats(z, DEV_SITES)
    row = dict(
        R2=p["test_global_R2_tension"], MAE=p["test_MAE_tension"], MAPE=p["test_MAPE_tension"],
        S=p["test_temporal_diff_skill_tension"], peak_MAE=p["test_peak_tension_MAE"],
        u90=p["test_peak_tension_underpred_rate_p90"],
        undermass90=undermass(p["test_peak_tension_MAE_p90"], p["test_peak_tension_bias_p90"]),
        u99=p["test_peak_tension_underpred_rate_p99"],
        undermass99=undermass(p["test_peak_tension_MAE_p99"], p["test_peak_tension_bias_p99"]),
        R2_grounded=p["test_contact_grounded_R2_median"],
        R2_touchdown=p["test_contact_touchdown_R2_median"],
        R2_suspended=p["test_contact_suspended_R2_median"],
        fl_ratio_dev=dev["ratio"], fl_relerr_dev=dev["relerr"], fl_up_dev=dev["up"],
        nonsnap_u90=ts[(90, "nonsnap")]["up"], nonsnap_bias90=ts[(90, "nonsnap")]["bias"],
        snap_events=len(ev),
        snap_capture_linemax=capture_summary([v[2] for v in ev.values()])["median"],
        snap_capture_own=capture_summary([v[0] for v in own.values()])["median"],
        snap_own_n=len(own),
    )
    for lc in (10, 11):
        s = site_peak_stats(z, (lc,))
        row[f"fl_ratio_loc{lc}"] = s["ratio"]
        row[f"fl_relerr_loc{lc}"] = s["relerr"]
    return row
