"""GENERATED by _build_linear_regression_nb.py -- DO NOT EDIT.

Stage-1 definitions copied VERBATIM from GAT_LSTM_NN_Publication_superresolution.ipynb,
one block per source cell (the cell id heads each block). Source-content hash: 00e848f601610783.

Only this header is new: the imports the cells expect, a small stand-in for
torch_geometric.data.Data when PyG is not installed, and the module-level tables the
split utilities read (set by linear_regression_lib.set_tables).
"""
from __future__ import annotations   # annotations such as `cfg: TrainingConfig` stay unevaluated

import copy
import math
import os
import random
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
from torch.utils.data import Dataset

try:
    from torch_geometric.data import Data
except ImportError:                    # build_mooring_graph only uses Data as a container
    class Data:
        def __init__(self, **kw):
            for k, v in kw.items():
                setattr(self, k, v)

        def clone(self):
            return copy.deepcopy(self)

# Read by valid_window_starts_inside_raw_interval / _snap_windows_in (cell 858f4194).
EXCLUDE_ARTIFACT_WINDOWS = True
ARTIFACT_SAMPLES = {}
SNAP_EVENT_TIMES = {}


# ===========================================================================
# VERBATIM from cell 66cf027f (whole cell)
# ===========================================================================
# ===================================================================
# MOORING LINE PROPERTIES  (Santjer et al. 2025 – Table 2)
# ===================================================================
MOORING_PROPERTIES = {
    "diameter":         0.068,        # [m]
    "area":             0.003619,     # [m2]
    "mass_per_length":  28.23,        # [kg/m]  (rhoA)
    "EA":               232.7e6,      # [N]     axial stiffness
    "Cd_n":             2.6,          # normal drag coefficient
    "Cd_t":             1.4,          # axial drag coefficient
    "k_b":              3.0e6,        # [Pa/m]  seabed spring stiffness
    "c_b":              3.0e5,        # [Pa*s/m] seabed damping
}


def build_mooring_graph(
    x0_nodes: torch.Tensor,
    z0_nodes: torch.Tensor,
    tension0_nodes: torch.Tensor,
    s0_nodes: torch.Tensor,
    water_depth: float,
    depths_current=None,
) -> Data:
    """
    Build a static PyG graph from the first time-step (t=0.1 s) of gnl_data1.

    Node positions (x0, z0) and initial tension come directly from the FE
    output at t=0.1 s, resampled to the desired node count.

    Static node features [N x 12]:
        0  s_over_L_line    normalised arc-length position [0..1]
        1  is_anchor        1 for r0
        2  is_fairlead      1 for rN
        3  is_intermediate  1 for interior nodes
        4  x0               initial x-coordinate [m]  (from gnl_data1 t=0)
        5  z0               initial z-coordinate [m]  (from gnl_data1 t=0)
        6  nodal_mass       lumped mass [kg]
        7  diameter         line diameter [m]
        8  area             cross-sectional area [m2]
        9  submerged_weight submerged weight contribution [N]
        10 z_bed            seabed elevation [m]  (= anchor z from gnl_data1)
        11 tension0         initial tension [N]  (from gnl_data1 t=0)

    Cd_n / Cd_t are constant line properties, NOT per-node features:
    stored globally as data.Cd_n / data.Cd_t (used by the drag force
    features computed in the dataset).

    Static edge features [E x 10]:
        0  segment_length             reference arc length [m]
        1  segment_length_over_L_line normalised segment length
        2  EA                         axial stiffness [N]
        3  mass_per_length            linear density [kg/m]
        4  diameter                   line diameter [m]
        5  tangent_x                  x-component of reference tangent
        6  tangent_z                  z-component of reference tangent
        7  edge_is_anchor               1.0 if anchor-side edge  else 0.0
        8  edge_is_intermediate         1.0 if internal edge     else 0.0
        9  edge_is_fairlead             1.0 if fairlead-side edge else 0.0

    Parameters
    ----------
    x0_nodes : torch.Tensor  shape [N]
        Initial x-coordinates from gnl_data1 row 0, resampled to N nodes.
    z0_nodes : torch.Tensor  shape [N]
        Initial z-coordinates from gnl_data1 row 0, resampled to N nodes.
    tension0_nodes : torch.Tensor  shape [N]
        Initial tension from gnl_data1 row 0, resampled to N nodes.
    s0_nodes : torch.Tensor  shape [N]
        Arc-length coordinate s [m] per node from gnl_data1 row 0, resampled to N nodes.
        s0_nodes[0] == 0 (anchor), s0_nodes[-1] == L_line (fairlead).
    water_depth : float
        Total water depth h0 [m] read from the input CSV for this case.
    depths_current : sequence, optional
        Current-profile depths d1..d5 [m] read from the input CSV for this case.
    """
    props = MOORING_PROPERTIES

    h = float(water_depth)
    if h <= 0.0:
        raise ValueError(f"water_depth must be positive, got {water_depth}.")


    # ------------------------------------------------------------------
    # 1. NODE POSITIONS  (from gnl_data1 first time step, t=0.1 s)
    # ------------------------------------------------------------------
    x0        = x0_nodes
    z0        = z0_nodes
    num_nodes = x0.shape[0]
    L_line    = float(s0_nodes[-1])   # actual arc length from gnl_data1

    # ------------------------------------------------------------------
    # 2. ARC-LENGTH COORDINATE along the mooring line
    # ------------------------------------------------------------------
    s_over_L = s0_nodes / L_line

    # ------------------------------------------------------------------
    # 3. NODE TYPE FLAGS
    # ------------------------------------------------------------------
    is_anchor       = torch.zeros(num_nodes)
    is_fairlead     = torch.zeros(num_nodes)
    is_intermediate = torch.ones(num_nodes)
    is_anchor[0]        = 1.0
    is_fairlead[-1]     = 1.0
    is_intermediate[0]  = 0.0
    is_intermediate[-1] = 0.0

    # ------------------------------------------------------------------
    # 4. PHYSICAL NODE ATTRIBUTES
    # ------------------------------------------------------------------
    seg_len_nom = L_line / (num_nodes - 1)

    nodal_mass = torch.full((num_nodes,), props["mass_per_length"] * seg_len_nom)
    nodal_mass[0]  *= 0.5
    nodal_mass[-1] *= 0.5

    diameter_node = torch.full((num_nodes,), props["diameter"])
    area_node     = torch.full((num_nodes,), props["area"])

    rho_water = 1025.0
    g         = 9.81
    submerged_weight_per_length = (
        props["mass_per_length"] - rho_water * props["area"]
    ) * g
    submerged_weight_node = torch.full(
        (num_nodes,), submerged_weight_per_length * seg_len_nom
    )
    submerged_weight_node[0]  *= 0.5
    submerged_weight_node[-1] *= 0.5

    z_bed      = float(z0[0])       # seabed level = anchor elevation
    z_bed_node = torch.full((num_nodes,), z_bed)

    # ------------------------------------------------------------------
    # 5. STATIC NODE FEATURE MATRIX  [N x 12]
    # ------------------------------------------------------------------
    x = torch.stack([
        s_over_L,              # 0
        is_anchor,             # 1
        is_fairlead,           # 2
        is_intermediate,       # 3
        x0,                    # 4
        z0,                    # 5
        nodal_mass,            # 6
        diameter_node,         # 7
        area_node,             # 8
        submerged_weight_node, # 9
        z_bed_node,            # 10
        tension0_nodes,        # 11
    ], dim=1)

    # ------------------------------------------------------------------
    # 6. GRAPH CONNECTIVITY  –  bidirectional chain
    # ------------------------------------------------------------------
    senders, receivers = [], []
    for i in range(num_nodes - 1):
        senders   += [i,     i + 1]
        receivers += [i + 1, i    ]
    edge_index = torch.tensor([senders, receivers], dtype=torch.long)

    # ------------------------------------------------------------------
    # 7. STATIC EDGE FEATURES  [E x 10]  (same for forward and backward)
    # ------------------------------------------------------------------
    edge_features = []
    for i in range(num_nodes - 1):
        dx = float(x0[i + 1] - x0[i])
        dz = float(z0[i + 1] - z0[i])
        seg_len    = math.sqrt(dx ** 2 + dz ** 2)
        seg_normed = seg_len / L_line
        tx = dx / seg_len if seg_len > 0 else 0.0
        tz = dz / seg_len if seg_len > 0 else 0.0
        edge_is_anchor       = 1.0 if i == 0             else 0.0
        edge_is_fairlead     = 1.0 if i == num_nodes - 2 else 0.0
        edge_is_intermediate = 1.0 if edge_is_anchor == 0.0 and edge_is_fairlead == 0.0 else 0.0
        feat = [
            seg_len,                   # 0
            seg_normed,                # 1
            props["EA"],               # 2
            props["mass_per_length"],  # 3
            props["diameter"],         # 4
            tx,                        # 5
            tz,                        # 6
            edge_is_anchor,            # 7
            edge_is_intermediate,      # 8
            edge_is_fairlead,          # 9
        ]
        edge_features.extend([feat, feat])    # forward + backward

    edge_attr = torch.tensor(edge_features, dtype=torch.float32)

    # ------------------------------------------------------------------
    # 8. GRAPH OBJECT
    # ------------------------------------------------------------------
    pos  = torch.stack([x0, z0], dim=1)
    data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, pos=pos)

    data.num_nodes_total  = num_nodes
    data.water_depth      = h
    data.line_length = L_line
    data.ea               = props["EA"]
    data.mass_per_length  = props["mass_per_length"]
    data.diameter         = props["diameter"]
    data.area             = props["area"]
    data.k_b              = props["k_b"]
    data.c_b              = props["c_b"]
    data.Cd_n             = props["Cd_n"]     # global, no longer a node feature
    data.Cd_t             = props["Cd_t"]     # global, no longer a node feature
    data.L0               = seg_len_nom        # uniform reference segment length [m]
    data.z_bed            = z_bed
    data.z_bed_node       = z_bed_node
    rope_positions        = [f"r{i}" for i in range(num_nodes)]
    data.rope_positions   = rope_positions
    data.depths_current   = None if depths_current is None else [float(d) for d in depths_current]

    return data


def print_graph_summary(data: Data):
    print("----- GRAPH SUMMARY -----")
    print(f"Water depth [m] : {data.water_depth:.1f}")
    print(f"L_line [m]      : {data.line_length:.2f}")
    print(f"EA [N]          : {data.ea:.3e}")
    print(f"Nodes           : {data.num_nodes_total}  ({', '.join(data.rope_positions)})")
    print()
    print(f"x shape       : {tuple(data.x.shape)}")
    print(f"edge_index    : {tuple(data.edge_index.shape)}")
    print(f"edge_attr     : {tuple(data.edge_attr.shape)}")
    print()
    print("Static node feature columns (12):")
    for i, c in enumerate([
        "s_over_L_line", "is_anchor", "is_fairlead", "is_intermediate",
        "x0", "z0", "nodal_mass", "diameter", "area",
        "submerged_weight", "z_bed", "tension0",
    ]):
        print(f"  {i:2d}  {c}")
    print()
    print("Static edge feature columns (10):")
    for i, c in enumerate([
        "segment_length", "segment_length_over_L_line", "EA",
        "mass_per_length", "diameter", "tangent_x", "tangent_z",
        "edge_is_anchor", "edge_is_intermediate", "edge_is_fairlead",
    ]):
        print(f"  {i}  {c}")
    print()
    print("Node positions (x, z) [m]:")
    print(data.pos)
    
# build_mooring_graph now requires x0_nodes, z0_nodes, tension0_nodes from gnl_data1.
# Call build_real_load_case_datasets() to construct graphs with real initial conditions.


# ===========================================================================
# VERBATIM from cell 4d3988c6 (whole cell)
# ===========================================================================
# -------------------------------------------------------------
# resampling utility
# -------------------------------------------------------------



def resample_fe_output(data_tN: torch.Tensor, target_N: int) -> torch.Tensor:
    """
    Resample FE output from N_orig nodes to target_N nodes along the
    normalised arc-length axis using linear interpolation (np.interp).

    The anchor (node 0) and fairlead (node -1) are always preserved
    exactly because they are the endpoints of the np.linspace grid.

    Parameters
    ----------
    data_tN : torch.Tensor  shape [T, N_orig]
        Full FE output for a single signal (e.g. x_abs, z_abs, tension)
        at N_orig nodes.
    target_N : int
        Desired number of output nodes (includes anchor and fairlead).

    Returns
    -------
    torch.Tensor  shape [T, target_N], dtype=torch.float32
    """
    T, N_orig = data_tN.shape
    if target_N == N_orig:
        return data_tN.to(torch.float32)

    src_pos = np.linspace(0.0, 1.0, N_orig, dtype=np.float32)
    tgt_pos = np.linspace(0.0, 1.0, target_N, dtype=np.float32)

    # Find left-neighbour index for each target position
    idx = np.searchsorted(src_pos, tgt_pos, side="right") - 1
    idx = np.clip(idx, 0, N_orig - 2)                      # [target_N]

    # Linear interpolation weight in [0, 1]
    weight = (tgt_pos - src_pos[idx]) / (src_pos[idx + 1] - src_pos[idx])
    weight = np.clip(weight, 0.0, 1.0).astype(np.float32)  # [target_N]

    arr   = data_tN.numpy()         # zero-copy view of float32 tensor
    left  = arr[:, idx]             # [T, target_N]
    right = arr[:, idx + 1]         # [T, target_N]
    out   = left + weight * (right - left)  # [T, target_N]

    return torch.from_numpy(out.astype(np.float32))


# ===========================================================================
# VERBATIM from cell a5660cf4 (whole cell)
# ===========================================================================
ENV_COL_NAMES = [
    "h0", "Hs", "Tp",
    "d1", "v1",
    "d2", "v2",
    "d3", "v3",
    "d4", "v4",
    "d5", "v5",
]

FEATURE_DT = 0.1     # [s] cache sampling interval (10 Hz)
RHO_WATER  = 1025.0  # [kg/m3] sea-water density (drag force features)


def _time_gradient(sig: torch.Tensor, dt: float = FEATURE_DT) -> torch.Tensor:
    """Finite-difference time derivative along dim 0.

    Central differences in the interior, one-sided at the window edges.
    sig : [T, N]  ->  [T, N]
    """
    grad = torch.empty_like(sig)
    grad[1:-1] = (sig[2:] - sig[:-2]) / (2.0 * dt)
    grad[0]    = (sig[1] - sig[0]) / dt
    grad[-1]   = (sig[-1] - sig[-2]) / dt
    return grad


def _unit_tangents(x_abs: torch.Tensor, z_abs: torch.Tensor):
    """Per-node unit tangent of the line from instantaneous positions.

    Central differences along the node dimension (dim 1), one-sided at
    the anchor/fairlead ends. x_abs, z_abs : [T, N] -> (tx, tz) [T, N].
    """
    def _node_diff(sig):
        d = torch.empty_like(sig)
        d[:, 1:-1] = sig[:, 2:] - sig[:, :-2]
        d[:, 0]    = sig[:, 1] - sig[:, 0]
        d[:, -1]   = sig[:, -1] - sig[:, -2]
        return d
    dx = _node_diff(x_abs)
    dz = _node_diff(z_abs)
    mag = torch.sqrt(dx * dx + dz * dz).clamp_min(1e-8)
    return dx / mag, dz / mag


# --- patch sr-17: motion-sensor noise (EVAL ONLY; OFF unless a sweep sets it) --
# A spec is a plain dict so it pickles cleanly into DataLoader workers:
#   {"id": int, "name": str,
#    "sigma_x", "sigma_z":   [m]    white noise on the MEASURED positions
#    "sigma_vx", "sigma_vz": [m/s]  white noise on the REPORTED velocities
#    "sigma_bx", "sigma_bz": [m]    constant per-station installation bias}
# None, or an all-zero spec, means clean.
SENSOR_NOISE_KEYS = ("sigma_x", "sigma_z", "sigma_vx", "sigma_vz",
                     "sigma_bx", "sigma_bz")


def sensor_noise_is_off(spec) -> bool:
    """True when the spec cannot perturb anything -- the fast path.

    Checked BEFORE a generator is constructed, so a clean pass draws no random
    numbers at all and is bit-identical to an unpatched run. That property is
    what makes the sigma = 0 reproduction gate meaningful.
    """
    if not spec:
        return True
    return all(float(spec.get(k, 0.0) or 0.0) == 0.0 for k in SENSOR_NOISE_KEYS)


def sensor_noise_generator(spec, lc_id, case_id, target_N, idx):
    """Deterministic per-(level, case, N_in, window) CPU generator.

    out_N is deliberately EXCLUDED from the seed. The perturbation is on the
    INPUT, which depends on N_in only, while evaluate_superres_grid sweeps
    out_N over ten values and run_interpolation_baseline repeats every one of
    them. All of those passes must see the SAME realisation, or the
    decoder-minus-baseline delta surface does not subtract.

    The mix is injective over the real ranges (lc < 16, case < 512, N_in < 32,
    window < 32768).

    WARNING -- do NOT simplify the finaliser away. torch's CPU generator
    IGNORES seed bits above bit 32: two seeds differing only above bit 32
    produce an IDENTICAL stream (verified on torch 2.11). The injective mix
    puts the discriminating bits high, so without the splitmix64 avalanche
    distinct LEVELS silently share a realisation and the entire sweep is void
    while looking perfectly healthy. Measured after the fix: 9600 distinct
    (level, N_in, loc, case, window) combinations -> 9600 distinct streams,
    0 collisions.
    """
    raw = ((((int(spec.get("id", 0)) * 32 + int(target_N)) * 512
             + int(case_id)) * 16 + int(lc_id)) * 32768 + int(idx))
    m = (1 << 64) - 1
    z = (raw + 0x9E3779B97F4A7C15) & m
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & m
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & m
    z = (z ^ (z >> 31)) & m
    g = torch.Generator()
    g.manual_seed(int(z & 0x7FFFFFFF))
    return g


def sensor_noise_apply(spec, gen, sig, sigma_key, bias_key, n_nodes):
    """Additive white noise (+ a constant per-station bias) in PHYSICAL units.

    sig : [W, N]. The bias is drawn once per station and held over the window,
    which is what an installation or calibration offset looks like.
    """
    sd = float(spec.get(sigma_key, 0.0) or 0.0)
    if sd > 0.0:
        sig = sig + torch.randn(sig.shape, generator=gen, dtype=sig.dtype) * sd
    if bias_key:
        sb = float(spec.get(bias_key, 0.0) or 0.0)
        if sb > 0.0:
            sig = sig + torch.randn((1, int(n_nodes)), generator=gen,
                                    dtype=sig.dtype) * sb
    return sig


class MooringSequenceDatasetPositionTension(Dataset):
    """
    Lazy sliding-window dataset for the PUBLICATION reconstruction task.

    Co-temporal motion -> tension: the input window and the target window are
    the SAME window_len rows of the case time series. There is no forecast
    horizon, and tension NEVER enters the inputs.

    Data is stored on disk as uncompressed .npy files and accessed via mmap.
    File handles are opened lazily inside each DataLoader worker on the first
    __getitem__ call, so ~30,000 dataset objects consume negligible RAM.

    Dynamic node features (9 base + 13 env = 22 total; env optional):
    ---------------------------------------------------------------
    0  x_abs             absolute horizontal node position [m]
    1  z_abs             absolute vertical node position [m]
    2  x_vel             horizontal node velocity [m/s] (finite difference)
    3  z_vel             vertical node velocity [m/s] (finite difference)
    4  contact_flag      binary: 1 if node touches seabed
    5  penetration_depth vertical penetration below seabed [m]
    6  bed_reaction_z    seabed reaction [N]: submerged weight +
                         (k_b*penetration - c_b*v_z) * contact area
    7  F_drag_t          axial quadratic drag force [N] (opposes v_t)
    8  F_drag_n          normal quadratic drag force [N] (opposes v_n)
    9+ h0, Hs, Tp, d1, v1, ..., d5, v5  env features (if use_env_features)

    NOTE: disabling use_velocity_features, use_drag_features or
    use_env_features changes the
    feature layout — cfg.node_continuous_idx / node_binary_idx must then be
    overridden to match in the run cell.

    Target features (1):
    --------------------
    0  tension  [N]  co-temporal with the input window
    """

    def __init__(
        self,
        graph_data,
        case_dir: Path,
        target_N: int,
        window_len: int,
        contact_tol: float = 1e-6,
        max_time_steps: int = None,
        use_env_features: bool = True,
        use_velocity_features: bool = True,
        use_drag_features: bool = True,
        out_N: Optional[int] = None,
    ):
        """
        Parameters
        ----------
        graph_data : torch_geometric.data.Data
            Static graph built by build_mooring_graph() for target_N nodes.
        case_dir : Path
            Directory containing x_abs.npy, z_abs.npy, tension.npy,
            reference.npy, env.npy for this (loc, case).
        target_N : int
            Number of nodes to resample to.
        window_len : int
            Co-temporal input/output window length in time steps (10 Hz).
        contact_tol : float
            Tolerance for seabed contact detection [m].
        max_time_steps : int, optional
            If set, expose only the first max_time_steps rows (debug mode).
        use_env_features : bool
            Include the 13 constant-per-case env columns in the inputs.
        use_velocity_features : bool
            Include finite-difference x/z velocities in the inputs.
        use_drag_features : bool
            Include quadratic axial/normal drag force features in the inputs.
        out_N : int, optional
            Stage-2 super-resolution: number of TARGET stations. None (default)
            means matched resolution, i.e. out_N == target_N, reproducing the
            Stage-1 behaviour exactly. When set, y_seq is resampled to out_N
            while the inputs stay at target_N = N_in. Mutable at runtime so the
            N_in x N_out evaluation grid can sweep it without rebuilding.
        """
        self.graph_data   = graph_data
        self._case_dir    = Path(case_dir)
        self._contact_tol = contact_tol
        self.target_N     = target_N
        self.window_len   = window_len
        self.use_env_features      = use_env_features
        self.use_velocity_features = use_velocity_features
        self.use_drag_features     = use_drag_features
# --- patch sr-01: Stage-2 target resolution (None = matched) ---
        self.out_N = out_N
# --- patch sr-17: motion-sensor noise spec + the identity used to seed it.
        # Both are set by MultiLoadCaseWindowSubset.__getitem__, exactly as
        # out_N is, so a sweep can change them between passes without
        # rebuilding (persistent_workers is False everywhere).
        self.sensor_noise = None
        self._sn_key = (0, 0)

        # Per-node effective segment length: end nodes carry HALF a segment,
        # matching the lumped convention in build_mooring_graph (nodal_mass
        # and submerged_weight are halved at anchor/fairlead). Used for the
        # contact and drag reference areas.
        node_len = torch.full((target_N,), float(graph_data.L0))
        node_len[0]  *= 0.5
        node_len[-1] *= 0.5
        self._node_len = node_len.unsqueeze(0)   # [1, N]

        if window_len < 2:
            raise ValueError(f"window_len must be >= 2, got {window_len}.")

        # Read only the array shape — numpy reads just the .npy header
        T_full = np.load(self._case_dir / "x_abs.npy", mmap_mode="r").shape[0]
        self.num_steps = T_full if max_time_steps is None else min(T_full, max_time_steps)
        self.num_nodes = target_N
        self.num_windows = self.num_steps - window_len + 1

        if self.num_windows <= 0:
            raise ValueError(
                f"Not enough time steps ({self.num_steps}) for window_len={window_len}."
            )

        # Load the small env row eagerly (13 floats — negligible memory)
        self._env_row = torch.tensor(
            np.load(self._case_dir / "env.npy"), dtype=torch.float32
        )   # [13]

        # Feature-count metadata (used by build_model_from_dataset_example)
        n_base = (5 + (2 if use_velocity_features else 0)
                    + (2 if use_drag_features else 0))
        self.n_dynamic_node_features = n_base + (len(ENV_COL_NAMES) if use_env_features else 0)
        self.n_dynamic_edge_features = 4
        self.n_targets               = 1

        # Mmap handles — None until first __getitem__ in this worker process
        self._mmap = None

    # ------------------------------------------------------------------
    # Feature-name metadata (used by print_dataset_summary and leak checks)
    # ------------------------------------------------------------------
    @property
    def dynamic_feature_names(self):
        names = ["x_abs", "z_abs"]
        if self.use_velocity_features:
            names += ["x_vel", "z_vel"]
        names += ["contact_flag", "penetration_depth", "bed_reaction_z"]
        if self.use_drag_features:
            names += ["F_drag_t", "F_drag_n"]
        if self.use_env_features:
            names += list(ENV_COL_NAMES)
        return names

    @property
    def dynamic_edge_feature_names(self):
        return [
            "edge_contact_fraction",
            "edge_penetration_mean",
            "edge_bed_reaction_mean",
            "edge_touchdown_flag",
        ]

    @property
    def target_feature_names(self):
        return ["tension"]

    def __len__(self):
        return self.num_windows

    def _open_mmap(self):
        """Open mmap handles for this worker process (called once per worker)."""
        self._mmap = {
            k: np.load(self._case_dir / f"{k}.npy", mmap_mode="r")
            for k in ("x_abs", "z_abs", "tension", "reference")
        }

    def __getitem__(self, idx):
        if idx < 0 or idx >= self.num_windows:
            raise IndexError(f"Window index {idx} out of range [0, {self.num_windows}).")

        # Open mmap lazily — each DataLoader worker opens its own file handles
        if self._mmap is None:
            self._open_mmap()

        start = idx
        end   = idx + self.window_len

        # 1. Read the required rows from mmap — OS page cache backed
        x_abs_w = torch.tensor(self._mmap["x_abs"][start:end],   dtype=torch.float32)
        z_abs_w = torch.tensor(self._mmap["z_abs"][start:end],   dtype=torch.float32)
        ten_w   = torch.tensor(self._mmap["tension"][start:end], dtype=torch.float32)

        # 2. Resample from N_FULL=21 nodes to target_N
        x_abs   = resample_fe_output(x_abs_w, self.target_N)    # [W, target_N]
        z_abs   = resample_fe_output(z_abs_w, self.target_N)
        _out_N = self.target_N if self.out_N is None else int(self.out_N)
        tension = resample_fe_output(ten_w,   _out_N)          # TARGET ONLY — never an input

        # --- patch sr-17: motion-sensor noise. Applied to the MEASURED
        #     positions, before anything is derived from them. Steps 3-7 below
        #     compute velocity, contact flag, penetration, bed reaction, both
        #     drag features and all four dynamic EDGE features from x_abs/z_abs,
        #     and the Kendall physics terms re-derive geometry from
        #     x_seq[..., 0:2], so a perturbation here propagates everywhere it
        #     should and nowhere it should not. `tension` above came from the
        #     CLEAN mmap, so the TARGET is never perturbed.
        _sn   = getattr(self, "sensor_noise", None)
        _sn_g = None
        _sn_clean = None
        if not sensor_noise_is_off(_sn):
            _sn_lc, _sn_cs = getattr(self, "_sn_key", (0, 0))
            _sn_g = sensor_noise_generator(_sn, _sn_lc, _sn_cs,
                                           self.target_N, idx)
            _sn_clean = (x_abs, z_abs)     # kept: see the velocity block
            x_abs = sensor_noise_apply(_sn, _sn_g, x_abs, "sigma_x",
                                       "sigma_bx", self.target_N)
            z_abs = sensor_noise_apply(_sn, _sn_g, z_abs, "sigma_z",
                                       "sigma_bz", self.target_N)

        # 3. Node velocities (always computed: bed damping + drag need them)
        _vx_src, _vz_src = x_abs, z_abs
        if _sn_g is not None and (float(_sn.get("sigma_vx", 0.0) or 0.0) > 0.0
                                  or float(_sn.get("sigma_vz", 0.0) or 0.0) > 0.0):
            # ARM P -- a fused GNSS-IMU reports velocity DIRECTLY (IMU +
            # Doppler), so its velocity error is INDEPENDENT of its position
            # error. Differentiate the CLEAN signal and give velocity its own
            # noise below, otherwise the channel would carry the position
            # noise derivative PLUS its own and would not be independent at all.
            # ARM C (sigma_v = 0) skips this: velocity is DERIVED from the noisy
            # position and inherits ~7x it at dt = 0.1 s -- the pessimistic bound.
            _vx_src, _vz_src = _sn_clean
        x_vel = _time_gradient(_vx_src)      # [W, N]
        z_vel = _time_gradient(_vz_src)
        if _sn_g is not None:
            x_vel = sensor_noise_apply(_sn, _sn_g, x_vel, "sigma_vx",
                                       None, self.target_N)
            z_vel = sensor_noise_apply(_sn, _sn_g, z_vel, "sigma_vz",
                                       None, self.target_N)

        # 4. Seabed interaction. Unified reaction for contacted nodes:
        #    submerged weight + (spring stiffness - vertical damping) x area.
        #    k_b [Pa/m] and c_b [Pa*s/m] are DISTRIBUTED quantities, so the
        #    projected contact area (diameter x L_eff; L_eff = L0, halved at
        #    the anchor/fairlead end nodes) restores Newtons; the
        #    -c_b*v_z damping term resists vertical motion while in contact.
        z_bed          = self.graph_data.z_bed_node.detach().cpu().unsqueeze(0)   # [1, N]
        contact_flag   = (z_abs <= z_bed + self._contact_tol).float()
        penetration    = torch.clamp(z_bed - z_abs, min=0.0)
        submerged_w    = self.graph_data.x[:, 9].detach().cpu().unsqueeze(0)      # [1, N]
        contact_area   = self.graph_data.diameter * self._node_len                # [1,N] m2
        v_z            = z_vel
        bed_reaction   = torch.where(
            contact_flag > 0.0,
            submerged_w + (self.graph_data.k_b * penetration
                           - self.graph_data.c_b * v_z) * contact_area,
            torch.zeros_like(submerged_w),
        )

        # 5. Quadratic drag force features: node velocity projected on the
        #    instantaneous line tangent/normal; negative sign = drag opposes
        #    the motion (v * |v| keeps the quadratic law sign-correct).
        if self.use_drag_features:
            tx, tz = _unit_tangents(x_abs, z_abs)
            v_t = x_vel * tx + z_vel * tz                    # axial component
            v_n = -x_vel * tz + z_vel * tx                   # normal component
            A_n = self.graph_data.diameter * self._node_len                # [1,N] projected
            A_t = math.pi * self.graph_data.diameter * self._node_len      # [1,N] wetted
            F_drag_t = -0.5 * RHO_WATER * self.graph_data.Cd_t * A_t * v_t * v_t.abs()
            F_drag_n = -0.5 * RHO_WATER * self.graph_data.Cd_n * A_n * v_n * v_n.abs()

        # 6. Dynamic node features [W, N, 22] (motion + derived + env; NO tension)
        feats = [x_abs, z_abs]
        if self.use_velocity_features:
            feats += [x_vel, z_vel]
        feats += [contact_flag, penetration, bed_reaction]
        if self.use_drag_features:
            feats += [F_drag_t, F_drag_n]
        dyn = torch.stack(feats, dim=-1)   # [W, N, 9]
        if self.use_env_features:
            env_exp = self._env_row.unsqueeze(0).unsqueeze(0).expand(
                self.window_len, self.target_N, -1
            )
            dyn = torch.cat([dyn, env_exp], dim=-1)   # [W, N, 22]

        # 7. Dynamic edge features [W, E, 4]
        src_nodes, tgt_nodes = self.graph_data.edge_index
        edge_dyn = torch.stack(
            [
                0.5 * (contact_flag[:, src_nodes] + contact_flag[:, tgt_nodes]),
                0.5 * (penetration[:, src_nodes]  + penetration[:, tgt_nodes]),
                0.5 * (bed_reaction[:, src_nodes]  + bed_reaction[:, tgt_nodes]),
                (contact_flag[:, src_nodes] != contact_flag[:, tgt_nodes]).float(),
            ],
            dim=-1,
        )   # [W, E, 4]

        return {
            "graph":     self.graph_data.clone(),
            "x_seq":     dyn,                        # [W, N, 22]
            "edge_seq":  edge_dyn,                   # [W, E, 4]
            "y_seq":     tension.unsqueeze(-1),      # [W, N, 1] — co-temporal tension
            "start_idx": idx,
            "out_N":     _out_N,
        }


def print_dataset_summary(dataset: MooringSequenceDatasetPositionTension):
    print("----- DATASET SUMMARY (reconstruction task) -----")
    print(f"Time steps : {dataset.num_steps}")
    print(f"Nodes      : {dataset.num_nodes}")
    print(f"Window len : {dataset.window_len} (co-temporal input/output)")
    print(f"Windows    : {len(dataset)}")
    print("Dynamic input features :", dataset.dynamic_feature_names)
    print("Dynamic edge  features :", dataset.dynamic_edge_feature_names)
    print("Target features        :", dataset.target_feature_names)
    sample = dataset[0]
    print("x_seq   :", tuple(sample["x_seq"].shape))
    print("edge_seq:", tuple(sample["edge_seq"].shape))
    print("y_seq   :", tuple(sample["y_seq"].shape))


# ===========================================================================
# VERBATIM from cell 858f4194 (whole cell)
# ===========================================================================
# -------------------------------------------------------------
# split utilities
# -------------------------------------------------------------

def get_window_span(dataset: MooringSequenceDatasetPositionTension) -> int:
    return dataset.window_len

def valid_window_starts_inside_raw_interval(
    dataset: MooringSequenceDatasetPositionTension,
    raw_start: int,
    raw_end_exclusive: int,
) -> List[int]:
    span = dataset.window_len
    lo = max(raw_start, 0)
    hi = min(raw_end_exclusive - span + 1, len(dataset))
    starts = list(range(lo, hi))
    # --- patch 19: per-window artifact exclusion ---
    # Drop starts whose [start, start+span) span covers a corrupt sample.
    # This is the single place every candidate list is built, so train,
    # val and test are all covered here.
    if not EXCLUDE_ARTIFACT_WINDOWS:
        return starts
    key = (int(dataset.graph_data.batch_location_id),
           int(dataset.graph_data.case_id))
    bad = ARTIFACT_SAMPLES.get(key)
    if not bad:
        return starts
    keep = []
    for s in starts:
        e = s + span
        if not any(s <= t < e for t in bad):
            keep.append(s)
    return keep

def chunk_raw_time_range(
    raw_start: int,
    raw_end_exclusive: int,
    block_len: int,
) -> List[Tuple[int, int]]:
    blocks = []
    cur = raw_start
    while cur < raw_end_exclusive:
        nxt = min(cur + block_len, raw_end_exclusive)
        blocks.append((cur, nxt))
        cur = nxt
    return blocks

def _sample_windows(starts, max_windows, rng):
    """Randomly subsample starts to at most max_windows entries.

    If max_windows is None or len(starts) <= max_windows, returns starts unchanged.
    Uses random.sample so the result is a new list (no mutation).
    """
    if max_windows is None or len(starts) <= max_windows:
        return starts
    return rng.sample(starts, max_windows)



def _snap_windows_in(dataset, starts):
    """Subset of `starts` whose window covers a catalogued snap event."""
    key = (int(dataset.graph_data.batch_location_id),
           int(dataset.graph_data.case_id))
    ev = SNAP_EVENT_TIMES.get(key)
    if not ev:
        return []
    span = dataset.window_len
    return [s for s in starts if any(s <= t < s + span for t in ev)]


def _snap_enriched_sample(dataset, starts, max_windows, rng, frac, seed,
                          pair_ncs=False):
    """Subsample `starts`, reserving a share of the budget for snaps.

    Snap events are ~2 % of candidate windows and would otherwise be
    thinned in proportion by the per-dataset budget. Reserving
    `frac` of the budget for snap-containing windows raises their share
    without touching the batch sampler, whose per-epoch draw is uniform
    over the pool this builds.

    TRAIN ONLY -- val and test keep calling _sample_windows, so the
    evaluation sets stay representative of operational conditions.

    The uniform draw is taken FIRST and always, so this function consumes
    exactly the same amount of the shared split RNG whatever `frac` is.
    Snap slots are then swapped in using a RNG derived deterministically
    from (seed, loc, case, N). Without that, a frac > 0 run would shift
    the shared stream and silently change which VAL and TEST windows are
    drawn, confounding any with/without-enrichment comparison.

    frac <= 0 reproduces _sample_windows exactly.
    """
    base = _sample_windows(starts, max_windows, rng)
    if frac <= 0.0 or max_windows is None or len(starts) <= max_windows:
        return base
    snap = _snap_windows_in(dataset, starts)
    if not snap:
        return base
    # --- patch sr-02: under paired draws the snap key must NOT depend on
    # target_N either, or a frac > 0 run would break the pairing it enforces.
    key = (int(seed) * 1000003
           + int(dataset.graph_data.batch_location_id) * 10007
           + int(dataset.graph_data.case_id) * 101
           + (0 if pair_ncs else int(dataset.target_N)))
    r_snap = random.Random(key)
    n_snap = min(len(snap), int(round(frac * max_windows)))
    picked = r_snap.sample(snap, n_snap)
    chosen = set(picked)
    picked += [s for s in base if s not in chosen][:max_windows - n_snap]
    picked.sort()
    return picked


def build_leakage_aware_splits(
    load_case_datasets: Dict[Tuple, MooringSequenceDatasetPositionTension],
    cfg: TrainingConfig,
) -> Dict[str, List]:
    """
    Build train / val / test window index lists.

    Dataset keys are (lc_id, case_id, target_N) 3-tuples.

    Split rules:
    - lc_id in train_lc_ids:
        * last 30% raw time per case -> test
        * first 70% raw time per case -> development (block-shuffled train/val)
    - lc_id in test_extra_lc_ids:
        * all windows -> test  (held-out locations)

    Each element of the returned lists is ((lc_id, case_id, target_N), window_idx).
    """
    # --- patch sr-02: per-dataset RNG for a paired N_in draw --------------
    # _shared_rng reproduces Stage 1 exactly (one stream consumed in dict order).
    # When pairing is on, each (lc, case) gets its OWN stream seeded WITHOUT
    # target_N, so all node counts of a case draw identical windows and an
    # identical train/val block shuffle.
    _shared_rng = random.Random(cfg.split_seed)
    _pair_ncs = bool(getattr(cfg, "pair_windows_across_node_counts", False))
    rng = _shared_rng
    split = {"train": [], "val": [], "test": []}

    # --- patch sr-06: cfg.node_counts alone selects the training topologies.
    # The dataset-build cell always constructs ALL node counts because the
    # N_in x N_out grid sweep needs every N_out graph present for the query
    # lookup; this filter keeps the SPLITS restricted to cfg.node_counts.
    # It MUST be applied to the dataset counts below as well: those counts are
    # the divisors of the per-dataset window budget, so leaving unused node
    # counts in them would silently shrink the pool (a 6-topology HPO run over
    # a 10-topology build would get half the windows it asked for).
    _use_ncs = set(int(n) for n in cfg.node_counts)

    # -- Per-dataset window budgets (cap-aware, stratified) ---------------
    # Derive actual dataset counts from the dict keys; no dependency on globals.
    # Per-dataset budgets create stratified sampling: each dataset contributes
    # proportionally. Reproducibility depends on cfg.split_seed.
    _train_keys = [k for k in load_case_datasets
                   if k[0] in cfg.train_lc_ids and k[2] in _use_ncs]
    _test_keys = [k for k in load_case_datasets
                   if k[0] in cfg.test_extra_lc_ids and k[2] in _use_ncs]
    _n_train_ds = max(1, len(_train_keys))
    _n_test_ds  = max(1, len(_test_keys))

    # Each training dataset contributes to both train and val; budget per dataset.
    _per_ds_train = (
        max(1, cfg.max_train_windows // _n_train_ds) if cfg.max_train_windows else None
    )
    _per_ds_val = (
        max(1, cfg.max_val_windows // _n_train_ds) if cfg.max_val_windows else None
    )
    _per_ds_test_held = (
        max(1, cfg.max_test_windows // _n_test_ds) if cfg.max_test_windows else None
    )
    # Time-based test windows from training locations share the same cap pool
    _per_ds_test_time = (
        max(1, cfg.max_test_windows // _n_train_ds) if cfg.max_test_windows else None
    )

    for (lc_id, case_id, target_N), ds in load_case_datasets.items():
        if int(target_N) not in _use_ncs:      # --- patch sr-06
            continue
        rng = (random.Random(cfg.split_seed * 1000003
                             + lc_id * 10007 + case_id * 101)
               if _pair_ncs else _shared_rng)
        num_steps = ds.num_steps

        if lc_id in cfg.train_lc_ids:
            test_raw_start = int(math.floor((1.0 - cfg.test_time_fraction) * num_steps))

            test_window_ids = valid_window_starts_inside_raw_interval(
                ds, raw_start=test_raw_start, raw_end_exclusive=num_steps,
            )
            test_window_ids = _sample_windows(test_window_ids, _per_ds_test_time, rng)
            split["test"].extend(
                ((lc_id, case_id, target_N), w) for w in test_window_ids
            )

            blocks = chunk_raw_time_range(
                raw_start=0, raw_end_exclusive=test_raw_start,
                block_len=cfg.raw_block_len,
            )
            valid_blocks = []
            for b_start, b_end in blocks:
                w_ids = valid_window_starts_inside_raw_interval(
                    ds, raw_start=b_start, raw_end_exclusive=b_end,
                )
                if w_ids:
                    valid_blocks.append((b_start, b_end, w_ids))

            rng.shuffle(valid_blocks)
            n_train = int(math.floor(cfg.train_fraction_within_dev_blocks * len(valid_blocks)))

            # Flatten all block windows per dataset, then sample once (true per-dataset cap)
            train_candidates = [w for _, _, ww in valid_blocks[:n_train] for w in ww]
            val_candidates   = [w for _, _, ww in valid_blocks[n_train:] for w in ww]
            split["train"].extend(
                ((lc_id, case_id, target_N), w)
                for w in _snap_enriched_sample(
                    ds, train_candidates, _per_ds_train, rng,
                    getattr(cfg, "snap_oversample_frac", 0.0),
                    cfg.split_seed, pair_ncs=_pair_ncs)
            )
            split["val"].extend(
                ((lc_id, case_id, target_N), w)
                for w in _sample_windows(val_candidates, _per_ds_val, rng)
            )

        elif lc_id in cfg.test_extra_lc_ids:
            # patch 22: the held-out locations MUST go through the same
            # artifact filter as the dev locations. Before this fix the
            # branch built list(range(len(ds))) and bypassed exclusion
            # entirely, putting 943 MN windows in the test set (job
            # 10521852: p99 thresholds destroyed, 0 feasible epochs/100).
            all_wins = valid_window_starts_inside_raw_interval(
                ds, raw_start=0, raw_end_exclusive=num_steps,
            )
            sampled  = _sample_windows(all_wins, _per_ds_test_held, rng)
            split["test"].extend(
                ((lc_id, case_id, target_N), w) for w in sampled
            )

        else:
            raise ValueError(f"LC {lc_id} is not assigned to any split rule.")

    return split

def print_split_summary(
    load_case_datasets: Dict[Tuple, MooringSequenceDatasetPositionTension],
    split_indices: Dict[str, List],
):
    """Print window counts per split, aggregated by (lc_id, target_N)."""
    print("----- SPLIT SUMMARY -----")
    for split_name, pairs in split_indices.items():
        # Aggregate by (lc_id, target_N) to keep output readable
        counts: Dict[Tuple, int] = {}
        for (lc_id, case_id, target_N), _ in pairs:
            key = (lc_id, target_N)
            counts[key] = counts.get(key, 0) + 1
        total = sum(counts.values())
        print(f"\n{split_name.upper()} total windows: {total}")
        for (lc_id, target_N) in sorted(counts):
            print(f"  LC {lc_id:02d} N={target_N:02d}: {counts[(lc_id, target_N)]} windows")


def _cap_split_windows(split_indices: Dict[str, List], cfg: TrainingConfig) -> Dict[str, List]:
    """Deterministically cap split sizes for small debug runs."""
    rng = random.Random(cfg.split_seed)
    _pair_ncs = bool(getattr(cfg, "pair_windows_across_node_counts", False))
    capped = {}
    caps = {
        "train": cfg.max_train_windows,
        "val": cfg.max_val_windows,
        "test": cfg.max_test_windows,
    }
    for split_name, pairs in split_indices.items():
        pairs = list(pairs)
        cap = caps.get(split_name)
        if cap is not None and len(pairs) > cap:
            if _pair_ncs:
                # Cap by (lc, case, window) GROUP so a retained window survives at
                # EVERY node count. Groups are kept whole and are all the same size
                # (every node count is built for every retained case), so the
                # per-node-count budget is cap // n_node_counts -- identical to the
                # unpaired scheme, only now the same windows at every N_in.
                from collections import defaultdict as _dd_cap
                _groups = _dd_cap(list)
                for _key, _w in pairs:
                    _groups[(_key[0], _key[1], _w)].append((_key, _w))
                _gk = sorted(_groups)
                rng.shuffle(_gk)
                _out, _n = [], 0
                for _g in _gk:
                    _members = _groups[_g]
                    if _n + len(_members) > cap:
                        continue          # never split a group across the cap
                    _out.extend(_members)
                    _n += len(_members)
                pairs = _out
            else:
                rng.shuffle(pairs)
                pairs = pairs[:cap]
            pairs.sort(key=lambda item: (item[0], item[1]))
        capped[split_name] = pairs
    return capped


def assert_windows_are_paired(split_indices: Dict[str, List], node_counts) -> None:
    """--- patch sr-02: verify every drawn window exists at EVERY node count.

    Cheap (a dict build over the pair lists) and worth running once per job:
    a silent pairing failure would confound the whole N_in axis of the
    super-resolution grid with the window draw.
    """
    from collections import defaultdict as _dd_chk
    want = set(int(n) for n in node_counts)
    for split_name, pairs in split_indices.items():
        seen = _dd_chk(set)
        for (lc_id, case_id, target_N), w in pairs:
            seen[(lc_id, case_id, w)].add(int(target_N))
        bad = [g for g, ncs in seen.items() if ncs != want]
        print(f"[paired] {split_name}: {len(seen):,} distinct windows x "
              f"{len(want)} node counts = {len(pairs):,} pairs; "
              f"{len(bad)} unpaired")
        if bad:
            raise AssertionError(
                f"{split_name}: {len(bad)} window(s) not present at every node "
                f"count, e.g. {bad[:3]} -- the N_in sweep would be confounded."
            )


# ===========================================================================
# VERBATIM from cell 81d71e4b (_sr22_filter_windows)
# ===========================================================================
def _sr22_filter_windows(index_pairs, drop, window_len):
    """patch sr-22: remove every (key, start) whose window covers a sample of `drop`.

    `drop` maps (loc, case) -> sample indices. A window spans [start, start + window_len)
    and its index IS its start sample (MooringSequenceDatasetPositionTension.__getitem__
    sets start = idx). Pure removal: the order of the surviving pairs is unchanged.
    """
    import bisect as _bisect
    _srt = {(int(k[0]), int(k[1])): sorted(int(t) for t in v) for k, v in drop.items()}
    out = []
    for key, w in index_pairs:
        b = _srt.get((int(key[0]), int(key[1])))
        if b:
            j = _bisect.bisect_left(b, int(w))
            if j < len(b) and b[j] < int(w) + int(window_len):
                continue
        out.append((key, w))
    return out


# ===========================================================================
# VERBATIM from cell 8e7ef9e9 (FeatureStandardizer)
# ===========================================================================
class FeatureStandardizer:
    """
    Per-feature z-score standardization for selected feature columns.

    Works with tensors shaped:
    - node inputs:   [window_len, N, F]
    - edge inputs:   [window_len, E, F]
    - targets:       [window_len, N, F]
    - static feats:  [N, F] / [E, F]
    """
    def __init__(self, feature_idx: Tuple[int, ...], eps: float = 1e-8):
        self.feature_idx = list(feature_idx)
        self.eps = eps
        self.mean = None
        self.std = None

    def fit_from_tensor_list(self, tensor_list: List[torch.Tensor]):
        """
        Aggregate across all dimensions except the last feature dimension.
        """
        selected = []
        for x in tensor_list:
            xs = x[..., self.feature_idx].reshape(-1, len(self.feature_idx))
            selected.append(xs)

        # float64: float32 cancellation gives constant columns like EA=2.3e8
        # a garbage nonzero std that defeats the constant-column guard
        big = torch.cat(selected, dim=0).double()
        self.mean = big.mean(dim=0).float()
        self.std = big.std(dim=0, unbiased=False).clamp_min(self.eps).float()

    def guard_constant_columns(self, rel: float = 1e-6):
        """Set std := 1 for (near-)constant columns.

        Static columns like EA, diameter, area, Cd are bit-identical across
        every graph -> std ~ 0. Without the guard those columns would divide
        by ~eps; with it they standardize to ~0 (centered, unit-scaled).
        Call after fitting.
        """
        const = self.std < (self.mean.abs() + 1.0) * rel
        self.std = torch.where(const, torch.ones_like(self.std), self.std)

    def transform(self, x: torch.Tensor) -> torch.Tensor:
        x = x.clone()
        x_sel = x[..., self.feature_idx]
        x[..., self.feature_idx] = (x_sel - self.mean.to(x.device)) / self.std.to(x.device)
        return x

    def inverse_transform(self, x: torch.Tensor) -> torch.Tensor:
        x = x.clone()
        x_sel = x[..., self.feature_idx]
        x[..., self.feature_idx] = x_sel * self.std.to(x.device) + self.mean.to(x.device)
        return x


# ===========================================================================
# VERBATIM from cell 9e030261 (compute_physical_metrics_per_target)
# ===========================================================================
@torch.no_grad()
def compute_physical_metrics_per_target(
    y_hat_norm: torch.Tensor,
    y_true_norm: torch.Tensor,
    target_norm: FeatureStandardizer,
    target_names: List[str],
    mape_eps: float = 1e-8,
    mape_min: float = 1000.0,
    peak_mape_min: float = 1000.0,
):
    """
    Inputs:
        y_hat_norm, y_true_norm: [window_len, N, output_dim] in normalised space.
        mape_min         : per-step MAPE threshold on |true_tension| [N].
        peak_mape_min    : peak MAPE threshold on |true_peak_tension| [N].

    Returns a flat dict. Caller-important keys:
        MAE / RMSE / R2              : {target_name: float}  (mean over time+nodes)
        ss_res / y_sum / y_sq / n_pts: {target_name: float}  (raw sums for global R2)
        MAPE                         : {tension: float|nan, tension_valid_frac: float}
        peak_tension_MAE/_RMSE/_bias/_underpred_rate/_MAPE : float
        peak_tension_abs_errors      : List[float]  (per-node, for global p95)
        temporal_diff_MAE_{name}          : float
        temporal_diff_MAE_flat_{name}     : float  (flat-line predictor baseline)
        temporal_diff_skill_{name}        : float  (model/flat; < 1 = genuine tracking)
    """
    import math as _math
    y_hat_phys  = target_norm.inverse_transform(y_hat_norm.detach().cpu().float())
    y_true_phys = target_norm.inverse_transform(y_true_norm.detach().cpu().float())
    error = y_hat_phys - y_true_phys   # [W, N, D]

    # Per-target MAE / RMSE (mean over time+nodes)
    mae  = error.abs().mean(dim=(0, 1))
    rmse = torch.sqrt((error ** 2).mean(dim=(0, 1)))

    # Per-window R2 (kept for backward compat; averaged by caller)
    y_true_mean_w = y_true_phys.mean(dim=(0, 1), keepdim=True)
    ss_res_w = (error ** 2).sum(dim=(0, 1))
    ss_tot_w = ((y_true_phys - y_true_mean_w) ** 2).sum(dim=(0, 1))
    r2_w     = 1.0 - ss_res_w / ss_tot_w.clamp_min(mape_eps)

    # Raw sums for global R2 accumulation in evaluate()
    ss_res_raw = (error ** 2).sum(dim=(0, 1))
    y_true_sum = y_true_phys.sum(dim=(0, 1))
    y_true_sq  = (y_true_phys ** 2).sum(dim=(0, 1))
    n_per_feat = float(y_true_phys.shape[0] * y_true_phys.shape[1])

    metrics = {
        "MAE":  {name: float(mae[i].item())   for i, name in enumerate(target_names)},
        "RMSE": {name: float(rmse[i].item())  for i, name in enumerate(target_names)},
        "R2":   {name: float(r2_w[i].item())  for i, name in enumerate(target_names)},
        "ss_res": {name: float(ss_res_raw[i].item()) for i, name in enumerate(target_names)},
        "y_sum":  {name: float(y_true_sum[i].item()) for i, name in enumerate(target_names)},
        "y_sq":   {name: float(y_true_sq[i].item())  for i, name in enumerate(target_names)},
        "n_pts":  n_per_feat,
        "MAPE": {},
    }

    # --- MAPE + peak-tension (tension only) ---
    if "tension" in target_names:
        t_idx  = target_names.index("tension")
        true_t = y_true_phys[..., t_idx]   # [W, N]
        pred_t = y_hat_phys[..., t_idx]

        mask = true_t.abs() > mape_min
        if mask.any():
            mape_val   = float(((pred_t - true_t).abs() / true_t.abs())[mask].mean().item() * 100.0)
            valid_frac = float(mask.float().mean().item())
        else:
            mape_val, valid_frac = float("nan"), 0.0
        metrics["MAPE"]["tension"]            = mape_val
        metrics["MAPE"]["tension_valid_frac"] = valid_frac

        true_peak = true_t.amax(dim=0)   # [N]
        pred_peak = pred_t.amax(dim=0)
        peak_err  = pred_peak - true_peak
        peak_abs  = peak_err.abs()
        metrics["peak_tension_MAE"]            = float(peak_abs.mean().item())
        metrics["peak_tension_RMSE"]           = float((peak_err ** 2).mean().sqrt().item())
        metrics["peak_tension_bias"]           = float(peak_err.mean().item())
        metrics["peak_tension_underpred_rate"] = float((peak_err < 0).float().mean().item() * 100.0)
        metrics["peak_tension_abs_errors"]     = peak_abs.tolist()
        metrics["peak_tension_true_peaks"]    = true_peak.tolist()
        metrics["peak_tension_signed_errors"] = peak_err.tolist()

        pmask = true_peak.abs() > peak_mape_min
        if pmask.any():
            metrics["peak_tension_MAPE"] = float(
                (peak_abs[pmask] / true_peak.abs()[pmask]).mean().item() * 100.0
            )
        else:
            metrics["peak_tension_MAPE"] = float("nan")
    else:
        metrics["peak_tension_abs_errors"] = []
        metrics["peak_tension_true_peaks"]    = []
        metrics["peak_tension_signed_errors"] = []

    # --- Temporal accuracy vs the flat-line baseline ---
    # A flat predictor's diff error equals |true_diff|, so skill = model/flat;
    # < 1 means the model genuinely tracks step-to-step changes (the thesis
    # forecaster sat at ~1.7, i.e. WORSE than flat — this metric is the direct
    # test that the reconstruction task fixed the temporal blind spot).
    if error.shape[0] > 1:
        pred_diff  = y_hat_phys[1:] - y_hat_phys[:-1]
        true_diff  = y_true_phys[1:] - y_true_phys[:-1]
        diff_error = (pred_diff - true_diff).abs()
        for i, name in enumerate(target_names):
            model_diff_mae = float(diff_error[..., i].mean().item())
            flat_diff_mae  = float(true_diff[..., i].abs().mean().item())
            metrics[f"temporal_diff_MAE_{name}"]      = model_diff_mae
            metrics[f"temporal_diff_MAE_flat_{name}"] = flat_diff_mae
            metrics[f"temporal_diff_skill_{name}"]    = (
                model_diff_mae / max(flat_diff_mae, 1e-12)
            )
    else:
        for name in target_names:
            metrics[f"temporal_diff_MAE_{name}"]      = float("nan")
            metrics[f"temporal_diff_MAE_flat_{name}"] = float("nan")
            metrics[f"temporal_diff_skill_{name}"]    = float("nan")

    return metrics
